mdm-azure-sql.hostname = ${mdm-azure-sql.hostname}
mdm-azure-sql.port = ${mdm-azure-sql.port}
mdm-azure-sql.database = ${mdm-azure-sql.database}

pump-azure-sql.hostname = ${pump-azure-sql.hostname}
pump-azure-sql.port = ${pump-azure-sql.port}
pump-azure-sql.database = ${pump-azure-sql.database}

speedlayer-azure-sql.hostname = ${speedlayer-azure-sql.hostname}
speedlayer-azure-sql.port = ${speedlayer-azure-sql.port}
speedlayer-azure-sql.database = ${speedlayer-azure-sql.database}
