use prepared;

CREATE TABLE fact_validated_event(
  durable_id varchar(36),
  organization_durable_key varchar(36),
  external_id bigint,
  persisted_date_utc timestamp,
  driver_durable_key varchar(36),
  vehicle_durable_key varchar(36),
  total_occurances bigint,
  total_time_seconds int,
  event_type_durable_key varchar(36),
  event_type_id bigint,
  driver_id bigint,
  asset_id bigint,
  value double,
  end_date_time timestamp,
  start_date_time timestamp,
  event_category varchar(255),
  start_odometer_kilometres double,
  start_position_timestamp timestamp,
  start_position_longitude double,
  start_position_latitude double,
  start_position_position_id bigint,
  start_position_speed_kilometres_per_hour double,
  end_odometer_kilometres double,
  end_position_timestamp timestamp,
  end_position_longitude double,
  end_position_latitude double,
  end_position_position_id bigint,
  end_position_speed_kilometres_per_hour double,
  value_type varchar(36),
  value_units varchar(36),
  location_id bigint,
  speed_limit double,
  validation_code int,
  problem_vehicle int)
PARTITIONED BY (year int, week_number int)
STORED AS ORC TBLPROPERTIES ("auto.purge"="true");