/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.epam.tcodata.models.avro.fact;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class AvroTachoParameterValue extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6665693005876487849L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AvroTachoParameterValue\",\"namespace\":\"com.epam.tcodata.models.avro.fact\",\"fields\":[{\"name\":\"value\",\"type\":[\"null\",\"int\"]},{\"name\":\"key\",\"type\":[\"null\",\"int\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AvroTachoParameterValue> ENCODER =
      new BinaryMessageEncoder<AvroTachoParameterValue>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AvroTachoParameterValue> DECODER =
      new BinaryMessageDecoder<AvroTachoParameterValue>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<AvroTachoParameterValue> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<AvroTachoParameterValue> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<AvroTachoParameterValue>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this AvroTachoParameterValue to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a AvroTachoParameterValue from a ByteBuffer. */
  public static AvroTachoParameterValue fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.Integer value;
  @Deprecated public java.lang.Integer key;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AvroTachoParameterValue() {}

  /**
   * All-args constructor.
   * @param value The new value for value
   * @param key The new value for key
   */
  public AvroTachoParameterValue(java.lang.Integer value, java.lang.Integer key) {
    this.value = value;
    this.key = key;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return value;
    case 1: return key;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: value = (java.lang.Integer)value$; break;
    case 1: key = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'value' field.
   * @return The value of the 'value' field.
   */
  public java.lang.Integer getValue() {
    return value;
  }

  /**
   * Sets the value of the 'value' field.
   * @param value the value to set.
   */
  public void setValue(java.lang.Integer value) {
    this.value = value;
  }

  /**
   * Gets the value of the 'key' field.
   * @return The value of the 'key' field.
   */
  public java.lang.Integer getKey() {
    return key;
  }

  /**
   * Sets the value of the 'key' field.
   * @param value the value to set.
   */
  public void setKey(java.lang.Integer value) {
    this.key = value;
  }

  /**
   * Creates a new AvroTachoParameterValue RecordBuilder.
   * @return A new AvroTachoParameterValue RecordBuilder
   */
  public static com.epam.tcodata.models.avro.fact.AvroTachoParameterValue.Builder newBuilder() {
    return new com.epam.tcodata.models.avro.fact.AvroTachoParameterValue.Builder();
  }

  /**
   * Creates a new AvroTachoParameterValue RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AvroTachoParameterValue RecordBuilder
   */
  public static com.epam.tcodata.models.avro.fact.AvroTachoParameterValue.Builder newBuilder(com.epam.tcodata.models.avro.fact.AvroTachoParameterValue.Builder other) {
    return new com.epam.tcodata.models.avro.fact.AvroTachoParameterValue.Builder(other);
  }

  /**
   * Creates a new AvroTachoParameterValue RecordBuilder by copying an existing AvroTachoParameterValue instance.
   * @param other The existing instance to copy.
   * @return A new AvroTachoParameterValue RecordBuilder
   */
  public static com.epam.tcodata.models.avro.fact.AvroTachoParameterValue.Builder newBuilder(com.epam.tcodata.models.avro.fact.AvroTachoParameterValue other) {
    return new com.epam.tcodata.models.avro.fact.AvroTachoParameterValue.Builder(other);
  }

  /**
   * RecordBuilder for AvroTachoParameterValue instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AvroTachoParameterValue>
    implements org.apache.avro.data.RecordBuilder<AvroTachoParameterValue> {

    private java.lang.Integer value;
    private java.lang.Integer key;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.epam.tcodata.models.avro.fact.AvroTachoParameterValue.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.value)) {
        this.value = data().deepCopy(fields()[0].schema(), other.value);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.key)) {
        this.key = data().deepCopy(fields()[1].schema(), other.key);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing AvroTachoParameterValue instance
     * @param other The existing instance to copy.
     */
    private Builder(com.epam.tcodata.models.avro.fact.AvroTachoParameterValue other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.value)) {
        this.value = data().deepCopy(fields()[0].schema(), other.value);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.key)) {
        this.key = data().deepCopy(fields()[1].schema(), other.key);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'value' field.
      * @return The value.
      */
    public java.lang.Integer getValue() {
      return value;
    }

    /**
      * Sets the value of the 'value' field.
      * @param value The value of 'value'.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.fact.AvroTachoParameterValue.Builder setValue(java.lang.Integer value) {
      validate(fields()[0], value);
      this.value = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'value' field has been set.
      * @return True if the 'value' field has been set, false otherwise.
      */
    public boolean hasValue() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'value' field.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.fact.AvroTachoParameterValue.Builder clearValue() {
      value = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'key' field.
      * @return The value.
      */
    public java.lang.Integer getKey() {
      return key;
    }

    /**
      * Sets the value of the 'key' field.
      * @param value The value of 'key'.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.fact.AvroTachoParameterValue.Builder setKey(java.lang.Integer value) {
      validate(fields()[1], value);
      this.key = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'key' field has been set.
      * @return True if the 'key' field has been set, false otherwise.
      */
    public boolean hasKey() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'key' field.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.fact.AvroTachoParameterValue.Builder clearKey() {
      key = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AvroTachoParameterValue build() {
      try {
        AvroTachoParameterValue record = new AvroTachoParameterValue();
        record.value = fieldSetFlags()[0] ? this.value : (java.lang.Integer) defaultValue(fields()[0]);
        record.key = fieldSetFlags()[1] ? this.key : (java.lang.Integer) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AvroTachoParameterValue>
    WRITER$ = (org.apache.avro.io.DatumWriter<AvroTachoParameterValue>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AvroTachoParameterValue>
    READER$ = (org.apache.avro.io.DatumReader<AvroTachoParameterValue>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
