/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.epam.tcodata.models.avro.fact;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class AvroPosition extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8681612877828552810L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AvroPosition\",\"namespace\":\"com.epam.tcodata.models.avro.fact\",\"fields\":[{\"name\":\"durableId\",\"type\":[\"null\",\"string\"]},{\"name\":\"ingestedDateUtc\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}},{\"name\":\"subscriptionId\",\"type\":[\"null\",\"long\"]},{\"name\":\"lineageCode\",\"type\":[\"null\",\"int\"]},{\"name\":\"driverDurableKey\",\"type\":[\"null\",\"string\"]},{\"name\":\"vehicleDurableKey\",\"type\":[\"null\",\"string\"]},{\"name\":\"schemaVersion\",\"type\":[\"null\",\"int\"],\"doc\":\"Transport message support: avro schema version number\"},{\"name\":\"positionId\",\"type\":[\"null\",\"long\"]},{\"name\":\"assetId\",\"type\":[\"null\",\"long\"]},{\"name\":\"driverId\",\"type\":[\"null\",\"long\"]},{\"name\":\"timestamp\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}},{\"name\":\"latitude\",\"type\":[\"null\",\"double\"]},{\"name\":\"longitude\",\"type\":[\"null\",\"double\"]},{\"name\":\"speedKilometresPerHour\",\"type\":[\"null\",\"double\"]},{\"name\":\"speedLimit\",\"type\":[\"null\",\"double\"]},{\"name\":\"altitudeMetres\",\"type\":[\"null\",\"int\"]},{\"name\":\"heading\",\"type\":[\"null\",\"int\"]},{\"name\":\"numberOfSatellites\",\"type\":[\"null\",\"int\"]},{\"name\":\"hdop\",\"type\":[\"null\",\"int\"]},{\"name\":\"vdop\",\"type\":[\"null\",\"int\"]},{\"name\":\"pdop\",\"type\":[\"null\",\"int\"]},{\"name\":\"ageOfReadingSeconds\",\"type\":[\"null\",\"long\"]},{\"name\":\"distanceSinceReadingKilometres\",\"type\":[\"null\",\"int\"]},{\"name\":\"ignitionOn\",\"type\":[\"null\",\"boolean\"]},{\"name\":\"odometerKilometres\",\"type\":[\"null\",\"double\"]},{\"name\":\"formattedAddress\",\"type\":[\"null\",\"string\"]},{\"name\":\"source\",\"type\":[\"null\",\"string\"]},{\"name\":\"avl\",\"type\":[\"null\",\"boolean\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AvroPosition> ENCODER =
      new BinaryMessageEncoder<AvroPosition>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AvroPosition> DECODER =
      new BinaryMessageDecoder<AvroPosition>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<AvroPosition> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<AvroPosition> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<AvroPosition>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this AvroPosition to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a AvroPosition from a ByteBuffer. */
  public static AvroPosition fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence durableId;
  @Deprecated public org.joda.time.DateTime ingestedDateUtc;
  @Deprecated public java.lang.Long subscriptionId;
  @Deprecated public java.lang.Integer lineageCode;
  @Deprecated public java.lang.CharSequence driverDurableKey;
  @Deprecated public java.lang.CharSequence vehicleDurableKey;
  /** Transport message support: avro schema version number */
  @Deprecated public java.lang.Integer schemaVersion;
  @Deprecated public java.lang.Long positionId;
  @Deprecated public java.lang.Long assetId;
  @Deprecated public java.lang.Long driverId;
  @Deprecated public org.joda.time.DateTime timestamp;
  @Deprecated public java.lang.Double latitude;
  @Deprecated public java.lang.Double longitude;
  @Deprecated public java.lang.Double speedKilometresPerHour;
  @Deprecated public java.lang.Double speedLimit;
  @Deprecated public java.lang.Integer altitudeMetres;
  @Deprecated public java.lang.Integer heading;
  @Deprecated public java.lang.Integer numberOfSatellites;
  @Deprecated public java.lang.Integer hdop;
  @Deprecated public java.lang.Integer vdop;
  @Deprecated public java.lang.Integer pdop;
  @Deprecated public java.lang.Long ageOfReadingSeconds;
  @Deprecated public java.lang.Integer distanceSinceReadingKilometres;
  @Deprecated public java.lang.Boolean ignitionOn;
  @Deprecated public java.lang.Double odometerKilometres;
  @Deprecated public java.lang.CharSequence formattedAddress;
  @Deprecated public java.lang.CharSequence source;
  @Deprecated public java.lang.Boolean avl;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AvroPosition() {}

  /**
   * All-args constructor.
   * @param durableId The new value for durableId
   * @param ingestedDateUtc The new value for ingestedDateUtc
   * @param subscriptionId The new value for subscriptionId
   * @param lineageCode The new value for lineageCode
   * @param driverDurableKey The new value for driverDurableKey
   * @param vehicleDurableKey The new value for vehicleDurableKey
   * @param schemaVersion Transport message support: avro schema version number
   * @param positionId The new value for positionId
   * @param assetId The new value for assetId
   * @param driverId The new value for driverId
   * @param timestamp The new value for timestamp
   * @param latitude The new value for latitude
   * @param longitude The new value for longitude
   * @param speedKilometresPerHour The new value for speedKilometresPerHour
   * @param speedLimit The new value for speedLimit
   * @param altitudeMetres The new value for altitudeMetres
   * @param heading The new value for heading
   * @param numberOfSatellites The new value for numberOfSatellites
   * @param hdop The new value for hdop
   * @param vdop The new value for vdop
   * @param pdop The new value for pdop
   * @param ageOfReadingSeconds The new value for ageOfReadingSeconds
   * @param distanceSinceReadingKilometres The new value for distanceSinceReadingKilometres
   * @param ignitionOn The new value for ignitionOn
   * @param odometerKilometres The new value for odometerKilometres
   * @param formattedAddress The new value for formattedAddress
   * @param source The new value for source
   * @param avl The new value for avl
   */
  public AvroPosition(java.lang.CharSequence durableId, org.joda.time.DateTime ingestedDateUtc, java.lang.Long subscriptionId, java.lang.Integer lineageCode, java.lang.CharSequence driverDurableKey, java.lang.CharSequence vehicleDurableKey, java.lang.Integer schemaVersion, java.lang.Long positionId, java.lang.Long assetId, java.lang.Long driverId, org.joda.time.DateTime timestamp, java.lang.Double latitude, java.lang.Double longitude, java.lang.Double speedKilometresPerHour, java.lang.Double speedLimit, java.lang.Integer altitudeMetres, java.lang.Integer heading, java.lang.Integer numberOfSatellites, java.lang.Integer hdop, java.lang.Integer vdop, java.lang.Integer pdop, java.lang.Long ageOfReadingSeconds, java.lang.Integer distanceSinceReadingKilometres, java.lang.Boolean ignitionOn, java.lang.Double odometerKilometres, java.lang.CharSequence formattedAddress, java.lang.CharSequence source, java.lang.Boolean avl) {
    this.durableId = durableId;
    this.ingestedDateUtc = ingestedDateUtc;
    this.subscriptionId = subscriptionId;
    this.lineageCode = lineageCode;
    this.driverDurableKey = driverDurableKey;
    this.vehicleDurableKey = vehicleDurableKey;
    this.schemaVersion = schemaVersion;
    this.positionId = positionId;
    this.assetId = assetId;
    this.driverId = driverId;
    this.timestamp = timestamp;
    this.latitude = latitude;
    this.longitude = longitude;
    this.speedKilometresPerHour = speedKilometresPerHour;
    this.speedLimit = speedLimit;
    this.altitudeMetres = altitudeMetres;
    this.heading = heading;
    this.numberOfSatellites = numberOfSatellites;
    this.hdop = hdop;
    this.vdop = vdop;
    this.pdop = pdop;
    this.ageOfReadingSeconds = ageOfReadingSeconds;
    this.distanceSinceReadingKilometres = distanceSinceReadingKilometres;
    this.ignitionOn = ignitionOn;
    this.odometerKilometres = odometerKilometres;
    this.formattedAddress = formattedAddress;
    this.source = source;
    this.avl = avl;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return durableId;
    case 1: return ingestedDateUtc;
    case 2: return subscriptionId;
    case 3: return lineageCode;
    case 4: return driverDurableKey;
    case 5: return vehicleDurableKey;
    case 6: return schemaVersion;
    case 7: return positionId;
    case 8: return assetId;
    case 9: return driverId;
    case 10: return timestamp;
    case 11: return latitude;
    case 12: return longitude;
    case 13: return speedKilometresPerHour;
    case 14: return speedLimit;
    case 15: return altitudeMetres;
    case 16: return heading;
    case 17: return numberOfSatellites;
    case 18: return hdop;
    case 19: return vdop;
    case 20: return pdop;
    case 21: return ageOfReadingSeconds;
    case 22: return distanceSinceReadingKilometres;
    case 23: return ignitionOn;
    case 24: return odometerKilometres;
    case 25: return formattedAddress;
    case 26: return source;
    case 27: return avl;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  protected static final org.apache.avro.data.TimeConversions.DateConversion DATE_CONVERSION = new org.apache.avro.data.TimeConversions.DateConversion();
  protected static final org.apache.avro.data.TimeConversions.TimeConversion TIME_CONVERSION = new org.apache.avro.data.TimeConversions.TimeConversion();
  protected static final org.apache.avro.data.TimeConversions.TimestampConversion TIMESTAMP_CONVERSION = new org.apache.avro.data.TimeConversions.TimestampConversion();
  protected static final org.apache.avro.Conversions.DecimalConversion DECIMAL_CONVERSION = new org.apache.avro.Conversions.DecimalConversion();

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      TIMESTAMP_CONVERSION,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      TIMESTAMP_CONVERSION,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: durableId = (java.lang.CharSequence)value$; break;
    case 1: ingestedDateUtc = (org.joda.time.DateTime)value$; break;
    case 2: subscriptionId = (java.lang.Long)value$; break;
    case 3: lineageCode = (java.lang.Integer)value$; break;
    case 4: driverDurableKey = (java.lang.CharSequence)value$; break;
    case 5: vehicleDurableKey = (java.lang.CharSequence)value$; break;
    case 6: schemaVersion = (java.lang.Integer)value$; break;
    case 7: positionId = (java.lang.Long)value$; break;
    case 8: assetId = (java.lang.Long)value$; break;
    case 9: driverId = (java.lang.Long)value$; break;
    case 10: timestamp = (org.joda.time.DateTime)value$; break;
    case 11: latitude = (java.lang.Double)value$; break;
    case 12: longitude = (java.lang.Double)value$; break;
    case 13: speedKilometresPerHour = (java.lang.Double)value$; break;
    case 14: speedLimit = (java.lang.Double)value$; break;
    case 15: altitudeMetres = (java.lang.Integer)value$; break;
    case 16: heading = (java.lang.Integer)value$; break;
    case 17: numberOfSatellites = (java.lang.Integer)value$; break;
    case 18: hdop = (java.lang.Integer)value$; break;
    case 19: vdop = (java.lang.Integer)value$; break;
    case 20: pdop = (java.lang.Integer)value$; break;
    case 21: ageOfReadingSeconds = (java.lang.Long)value$; break;
    case 22: distanceSinceReadingKilometres = (java.lang.Integer)value$; break;
    case 23: ignitionOn = (java.lang.Boolean)value$; break;
    case 24: odometerKilometres = (java.lang.Double)value$; break;
    case 25: formattedAddress = (java.lang.CharSequence)value$; break;
    case 26: source = (java.lang.CharSequence)value$; break;
    case 27: avl = (java.lang.Boolean)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'durableId' field.
   * @return The value of the 'durableId' field.
   */
  public java.lang.CharSequence getDurableId() {
    return durableId;
  }

  /**
   * Sets the value of the 'durableId' field.
   * @param value the value to set.
   */
  public void setDurableId(java.lang.CharSequence value) {
    this.durableId = value;
  }

  /**
   * Gets the value of the 'ingestedDateUtc' field.
   * @return The value of the 'ingestedDateUtc' field.
   */
  public org.joda.time.DateTime getIngestedDateUtc() {
    return ingestedDateUtc;
  }

  /**
   * Sets the value of the 'ingestedDateUtc' field.
   * @param value the value to set.
   */
  public void setIngestedDateUtc(org.joda.time.DateTime value) {
    this.ingestedDateUtc = value;
  }

  /**
   * Gets the value of the 'subscriptionId' field.
   * @return The value of the 'subscriptionId' field.
   */
  public java.lang.Long getSubscriptionId() {
    return subscriptionId;
  }

  /**
   * Sets the value of the 'subscriptionId' field.
   * @param value the value to set.
   */
  public void setSubscriptionId(java.lang.Long value) {
    this.subscriptionId = value;
  }

  /**
   * Gets the value of the 'lineageCode' field.
   * @return The value of the 'lineageCode' field.
   */
  public java.lang.Integer getLineageCode() {
    return lineageCode;
  }

  /**
   * Sets the value of the 'lineageCode' field.
   * @param value the value to set.
   */
  public void setLineageCode(java.lang.Integer value) {
    this.lineageCode = value;
  }

  /**
   * Gets the value of the 'driverDurableKey' field.
   * @return The value of the 'driverDurableKey' field.
   */
  public java.lang.CharSequence getDriverDurableKey() {
    return driverDurableKey;
  }

  /**
   * Sets the value of the 'driverDurableKey' field.
   * @param value the value to set.
   */
  public void setDriverDurableKey(java.lang.CharSequence value) {
    this.driverDurableKey = value;
  }

  /**
   * Gets the value of the 'vehicleDurableKey' field.
   * @return The value of the 'vehicleDurableKey' field.
   */
  public java.lang.CharSequence getVehicleDurableKey() {
    return vehicleDurableKey;
  }

  /**
   * Sets the value of the 'vehicleDurableKey' field.
   * @param value the value to set.
   */
  public void setVehicleDurableKey(java.lang.CharSequence value) {
    this.vehicleDurableKey = value;
  }

  /**
   * Gets the value of the 'schemaVersion' field.
   * @return Transport message support: avro schema version number
   */
  public java.lang.Integer getSchemaVersion() {
    return schemaVersion;
  }

  /**
   * Sets the value of the 'schemaVersion' field.
   * Transport message support: avro schema version number
   * @param value the value to set.
   */
  public void setSchemaVersion(java.lang.Integer value) {
    this.schemaVersion = value;
  }

  /**
   * Gets the value of the 'positionId' field.
   * @return The value of the 'positionId' field.
   */
  public java.lang.Long getPositionId() {
    return positionId;
  }

  /**
   * Sets the value of the 'positionId' field.
   * @param value the value to set.
   */
  public void setPositionId(java.lang.Long value) {
    this.positionId = value;
  }

  /**
   * Gets the value of the 'assetId' field.
   * @return The value of the 'assetId' field.
   */
  public java.lang.Long getAssetId() {
    return assetId;
  }

  /**
   * Sets the value of the 'assetId' field.
   * @param value the value to set.
   */
  public void setAssetId(java.lang.Long value) {
    this.assetId = value;
  }

  /**
   * Gets the value of the 'driverId' field.
   * @return The value of the 'driverId' field.
   */
  public java.lang.Long getDriverId() {
    return driverId;
  }

  /**
   * Sets the value of the 'driverId' field.
   * @param value the value to set.
   */
  public void setDriverId(java.lang.Long value) {
    this.driverId = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return The value of the 'timestamp' field.
   */
  public org.joda.time.DateTime getTimestamp() {
    return timestamp;
  }

  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(org.joda.time.DateTime value) {
    this.timestamp = value;
  }

  /**
   * Gets the value of the 'latitude' field.
   * @return The value of the 'latitude' field.
   */
  public java.lang.Double getLatitude() {
    return latitude;
  }

  /**
   * Sets the value of the 'latitude' field.
   * @param value the value to set.
   */
  public void setLatitude(java.lang.Double value) {
    this.latitude = value;
  }

  /**
   * Gets the value of the 'longitude' field.
   * @return The value of the 'longitude' field.
   */
  public java.lang.Double getLongitude() {
    return longitude;
  }

  /**
   * Sets the value of the 'longitude' field.
   * @param value the value to set.
   */
  public void setLongitude(java.lang.Double value) {
    this.longitude = value;
  }

  /**
   * Gets the value of the 'speedKilometresPerHour' field.
   * @return The value of the 'speedKilometresPerHour' field.
   */
  public java.lang.Double getSpeedKilometresPerHour() {
    return speedKilometresPerHour;
  }

  /**
   * Sets the value of the 'speedKilometresPerHour' field.
   * @param value the value to set.
   */
  public void setSpeedKilometresPerHour(java.lang.Double value) {
    this.speedKilometresPerHour = value;
  }

  /**
   * Gets the value of the 'speedLimit' field.
   * @return The value of the 'speedLimit' field.
   */
  public java.lang.Double getSpeedLimit() {
    return speedLimit;
  }

  /**
   * Sets the value of the 'speedLimit' field.
   * @param value the value to set.
   */
  public void setSpeedLimit(java.lang.Double value) {
    this.speedLimit = value;
  }

  /**
   * Gets the value of the 'altitudeMetres' field.
   * @return The value of the 'altitudeMetres' field.
   */
  public java.lang.Integer getAltitudeMetres() {
    return altitudeMetres;
  }

  /**
   * Sets the value of the 'altitudeMetres' field.
   * @param value the value to set.
   */
  public void setAltitudeMetres(java.lang.Integer value) {
    this.altitudeMetres = value;
  }

  /**
   * Gets the value of the 'heading' field.
   * @return The value of the 'heading' field.
   */
  public java.lang.Integer getHeading() {
    return heading;
  }

  /**
   * Sets the value of the 'heading' field.
   * @param value the value to set.
   */
  public void setHeading(java.lang.Integer value) {
    this.heading = value;
  }

  /**
   * Gets the value of the 'numberOfSatellites' field.
   * @return The value of the 'numberOfSatellites' field.
   */
  public java.lang.Integer getNumberOfSatellites() {
    return numberOfSatellites;
  }

  /**
   * Sets the value of the 'numberOfSatellites' field.
   * @param value the value to set.
   */
  public void setNumberOfSatellites(java.lang.Integer value) {
    this.numberOfSatellites = value;
  }

  /**
   * Gets the value of the 'hdop' field.
   * @return The value of the 'hdop' field.
   */
  public java.lang.Integer getHdop() {
    return hdop;
  }

  /**
   * Sets the value of the 'hdop' field.
   * @param value the value to set.
   */
  public void setHdop(java.lang.Integer value) {
    this.hdop = value;
  }

  /**
   * Gets the value of the 'vdop' field.
   * @return The value of the 'vdop' field.
   */
  public java.lang.Integer getVdop() {
    return vdop;
  }

  /**
   * Sets the value of the 'vdop' field.
   * @param value the value to set.
   */
  public void setVdop(java.lang.Integer value) {
    this.vdop = value;
  }

  /**
   * Gets the value of the 'pdop' field.
   * @return The value of the 'pdop' field.
   */
  public java.lang.Integer getPdop() {
    return pdop;
  }

  /**
   * Sets the value of the 'pdop' field.
   * @param value the value to set.
   */
  public void setPdop(java.lang.Integer value) {
    this.pdop = value;
  }

  /**
   * Gets the value of the 'ageOfReadingSeconds' field.
   * @return The value of the 'ageOfReadingSeconds' field.
   */
  public java.lang.Long getAgeOfReadingSeconds() {
    return ageOfReadingSeconds;
  }

  /**
   * Sets the value of the 'ageOfReadingSeconds' field.
   * @param value the value to set.
   */
  public void setAgeOfReadingSeconds(java.lang.Long value) {
    this.ageOfReadingSeconds = value;
  }

  /**
   * Gets the value of the 'distanceSinceReadingKilometres' field.
   * @return The value of the 'distanceSinceReadingKilometres' field.
   */
  public java.lang.Integer getDistanceSinceReadingKilometres() {
    return distanceSinceReadingKilometres;
  }

  /**
   * Sets the value of the 'distanceSinceReadingKilometres' field.
   * @param value the value to set.
   */
  public void setDistanceSinceReadingKilometres(java.lang.Integer value) {
    this.distanceSinceReadingKilometres = value;
  }

  /**
   * Gets the value of the 'ignitionOn' field.
   * @return The value of the 'ignitionOn' field.
   */
  public java.lang.Boolean getIgnitionOn() {
    return ignitionOn;
  }

  /**
   * Sets the value of the 'ignitionOn' field.
   * @param value the value to set.
   */
  public void setIgnitionOn(java.lang.Boolean value) {
    this.ignitionOn = value;
  }

  /**
   * Gets the value of the 'odometerKilometres' field.
   * @return The value of the 'odometerKilometres' field.
   */
  public java.lang.Double getOdometerKilometres() {
    return odometerKilometres;
  }

  /**
   * Sets the value of the 'odometerKilometres' field.
   * @param value the value to set.
   */
  public void setOdometerKilometres(java.lang.Double value) {
    this.odometerKilometres = value;
  }

  /**
   * Gets the value of the 'formattedAddress' field.
   * @return The value of the 'formattedAddress' field.
   */
  public java.lang.CharSequence getFormattedAddress() {
    return formattedAddress;
  }

  /**
   * Sets the value of the 'formattedAddress' field.
   * @param value the value to set.
   */
  public void setFormattedAddress(java.lang.CharSequence value) {
    this.formattedAddress = value;
  }

  /**
   * Gets the value of the 'source' field.
   * @return The value of the 'source' field.
   */
  public java.lang.CharSequence getSource() {
    return source;
  }

  /**
   * Sets the value of the 'source' field.
   * @param value the value to set.
   */
  public void setSource(java.lang.CharSequence value) {
    this.source = value;
  }

  /**
   * Gets the value of the 'avl' field.
   * @return The value of the 'avl' field.
   */
  public java.lang.Boolean getAvl() {
    return avl;
  }

  /**
   * Sets the value of the 'avl' field.
   * @param value the value to set.
   */
  public void setAvl(java.lang.Boolean value) {
    this.avl = value;
  }

  /**
   * Creates a new AvroPosition RecordBuilder.
   * @return A new AvroPosition RecordBuilder
   */
  public static com.epam.tcodata.models.avro.fact.AvroPosition.Builder newBuilder() {
    return new com.epam.tcodata.models.avro.fact.AvroPosition.Builder();
  }

  /**
   * Creates a new AvroPosition RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AvroPosition RecordBuilder
   */
  public static com.epam.tcodata.models.avro.fact.AvroPosition.Builder newBuilder(com.epam.tcodata.models.avro.fact.AvroPosition.Builder other) {
    return new com.epam.tcodata.models.avro.fact.AvroPosition.Builder(other);
  }

  /**
   * Creates a new AvroPosition RecordBuilder by copying an existing AvroPosition instance.
   * @param other The existing instance to copy.
   * @return A new AvroPosition RecordBuilder
   */
  public static com.epam.tcodata.models.avro.fact.AvroPosition.Builder newBuilder(com.epam.tcodata.models.avro.fact.AvroPosition other) {
    return new com.epam.tcodata.models.avro.fact.AvroPosition.Builder(other);
  }

  /**
   * RecordBuilder for AvroPosition instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AvroPosition>
    implements org.apache.avro.data.RecordBuilder<AvroPosition> {

    private java.lang.CharSequence durableId;
    private org.joda.time.DateTime ingestedDateUtc;
    private java.lang.Long subscriptionId;
    private java.lang.Integer lineageCode;
    private java.lang.CharSequence driverDurableKey;
    private java.lang.CharSequence vehicleDurableKey;
    /** Transport message support: avro schema version number */
    private java.lang.Integer schemaVersion;
    private java.lang.Long positionId;
    private java.lang.Long assetId;
    private java.lang.Long driverId;
    private org.joda.time.DateTime timestamp;
    private java.lang.Double latitude;
    private java.lang.Double longitude;
    private java.lang.Double speedKilometresPerHour;
    private java.lang.Double speedLimit;
    private java.lang.Integer altitudeMetres;
    private java.lang.Integer heading;
    private java.lang.Integer numberOfSatellites;
    private java.lang.Integer hdop;
    private java.lang.Integer vdop;
    private java.lang.Integer pdop;
    private java.lang.Long ageOfReadingSeconds;
    private java.lang.Integer distanceSinceReadingKilometres;
    private java.lang.Boolean ignitionOn;
    private java.lang.Double odometerKilometres;
    private java.lang.CharSequence formattedAddress;
    private java.lang.CharSequence source;
    private java.lang.Boolean avl;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.epam.tcodata.models.avro.fact.AvroPosition.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.durableId)) {
        this.durableId = data().deepCopy(fields()[0].schema(), other.durableId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.ingestedDateUtc)) {
        this.ingestedDateUtc = data().deepCopy(fields()[1].schema(), other.ingestedDateUtc);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.subscriptionId)) {
        this.subscriptionId = data().deepCopy(fields()[2].schema(), other.subscriptionId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.lineageCode)) {
        this.lineageCode = data().deepCopy(fields()[3].schema(), other.lineageCode);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.driverDurableKey)) {
        this.driverDurableKey = data().deepCopy(fields()[4].schema(), other.driverDurableKey);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.vehicleDurableKey)) {
        this.vehicleDurableKey = data().deepCopy(fields()[5].schema(), other.vehicleDurableKey);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.schemaVersion)) {
        this.schemaVersion = data().deepCopy(fields()[6].schema(), other.schemaVersion);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.positionId)) {
        this.positionId = data().deepCopy(fields()[7].schema(), other.positionId);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.assetId)) {
        this.assetId = data().deepCopy(fields()[8].schema(), other.assetId);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.driverId)) {
        this.driverId = data().deepCopy(fields()[9].schema(), other.driverId);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[10].schema(), other.timestamp);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.latitude)) {
        this.latitude = data().deepCopy(fields()[11].schema(), other.latitude);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.longitude)) {
        this.longitude = data().deepCopy(fields()[12].schema(), other.longitude);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.speedKilometresPerHour)) {
        this.speedKilometresPerHour = data().deepCopy(fields()[13].schema(), other.speedKilometresPerHour);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.speedLimit)) {
        this.speedLimit = data().deepCopy(fields()[14].schema(), other.speedLimit);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.altitudeMetres)) {
        this.altitudeMetres = data().deepCopy(fields()[15].schema(), other.altitudeMetres);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.heading)) {
        this.heading = data().deepCopy(fields()[16].schema(), other.heading);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.numberOfSatellites)) {
        this.numberOfSatellites = data().deepCopy(fields()[17].schema(), other.numberOfSatellites);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.hdop)) {
        this.hdop = data().deepCopy(fields()[18].schema(), other.hdop);
        fieldSetFlags()[18] = true;
      }
      if (isValidValue(fields()[19], other.vdop)) {
        this.vdop = data().deepCopy(fields()[19].schema(), other.vdop);
        fieldSetFlags()[19] = true;
      }
      if (isValidValue(fields()[20], other.pdop)) {
        this.pdop = data().deepCopy(fields()[20].schema(), other.pdop);
        fieldSetFlags()[20] = true;
      }
      if (isValidValue(fields()[21], other.ageOfReadingSeconds)) {
        this.ageOfReadingSeconds = data().deepCopy(fields()[21].schema(), other.ageOfReadingSeconds);
        fieldSetFlags()[21] = true;
      }
      if (isValidValue(fields()[22], other.distanceSinceReadingKilometres)) {
        this.distanceSinceReadingKilometres = data().deepCopy(fields()[22].schema(), other.distanceSinceReadingKilometres);
        fieldSetFlags()[22] = true;
      }
      if (isValidValue(fields()[23], other.ignitionOn)) {
        this.ignitionOn = data().deepCopy(fields()[23].schema(), other.ignitionOn);
        fieldSetFlags()[23] = true;
      }
      if (isValidValue(fields()[24], other.odometerKilometres)) {
        this.odometerKilometres = data().deepCopy(fields()[24].schema(), other.odometerKilometres);
        fieldSetFlags()[24] = true;
      }
      if (isValidValue(fields()[25], other.formattedAddress)) {
        this.formattedAddress = data().deepCopy(fields()[25].schema(), other.formattedAddress);
        fieldSetFlags()[25] = true;
      }
      if (isValidValue(fields()[26], other.source)) {
        this.source = data().deepCopy(fields()[26].schema(), other.source);
        fieldSetFlags()[26] = true;
      }
      if (isValidValue(fields()[27], other.avl)) {
        this.avl = data().deepCopy(fields()[27].schema(), other.avl);
        fieldSetFlags()[27] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing AvroPosition instance
     * @param other The existing instance to copy.
     */
    private Builder(com.epam.tcodata.models.avro.fact.AvroPosition other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.durableId)) {
        this.durableId = data().deepCopy(fields()[0].schema(), other.durableId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.ingestedDateUtc)) {
        this.ingestedDateUtc = data().deepCopy(fields()[1].schema(), other.ingestedDateUtc);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.subscriptionId)) {
        this.subscriptionId = data().deepCopy(fields()[2].schema(), other.subscriptionId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.lineageCode)) {
        this.lineageCode = data().deepCopy(fields()[3].schema(), other.lineageCode);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.driverDurableKey)) {
        this.driverDurableKey = data().deepCopy(fields()[4].schema(), other.driverDurableKey);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.vehicleDurableKey)) {
        this.vehicleDurableKey = data().deepCopy(fields()[5].schema(), other.vehicleDurableKey);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.schemaVersion)) {
        this.schemaVersion = data().deepCopy(fields()[6].schema(), other.schemaVersion);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.positionId)) {
        this.positionId = data().deepCopy(fields()[7].schema(), other.positionId);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.assetId)) {
        this.assetId = data().deepCopy(fields()[8].schema(), other.assetId);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.driverId)) {
        this.driverId = data().deepCopy(fields()[9].schema(), other.driverId);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[10].schema(), other.timestamp);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.latitude)) {
        this.latitude = data().deepCopy(fields()[11].schema(), other.latitude);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.longitude)) {
        this.longitude = data().deepCopy(fields()[12].schema(), other.longitude);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.speedKilometresPerHour)) {
        this.speedKilometresPerHour = data().deepCopy(fields()[13].schema(), other.speedKilometresPerHour);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.speedLimit)) {
        this.speedLimit = data().deepCopy(fields()[14].schema(), other.speedLimit);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.altitudeMetres)) {
        this.altitudeMetres = data().deepCopy(fields()[15].schema(), other.altitudeMetres);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.heading)) {
        this.heading = data().deepCopy(fields()[16].schema(), other.heading);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.numberOfSatellites)) {
        this.numberOfSatellites = data().deepCopy(fields()[17].schema(), other.numberOfSatellites);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.hdop)) {
        this.hdop = data().deepCopy(fields()[18].schema(), other.hdop);
        fieldSetFlags()[18] = true;
      }
      if (isValidValue(fields()[19], other.vdop)) {
        this.vdop = data().deepCopy(fields()[19].schema(), other.vdop);
        fieldSetFlags()[19] = true;
      }
      if (isValidValue(fields()[20], other.pdop)) {
        this.pdop = data().deepCopy(fields()[20].schema(), other.pdop);
        fieldSetFlags()[20] = true;
      }
      if (isValidValue(fields()[21], other.ageOfReadingSeconds)) {
        this.ageOfReadingSeconds = data().deepCopy(fields()[21].schema(), other.ageOfReadingSeconds);
        fieldSetFlags()[21] = true;
      }
      if (isValidValue(fields()[22], other.distanceSinceReadingKilometres)) {
        this.distanceSinceReadingKilometres = data().deepCopy(fields()[22].schema(), other.distanceSinceReadingKilometres);
        fieldSetFlags()[22] = true;
      }
      if (isValidValue(fields()[23], other.ignitionOn)) {
        this.ignitionOn = data().deepCopy(fields()[23].schema(), other.ignitionOn);
        fieldSetFlags()[23] = true;
      }
      if (isValidValue(fields()[24], other.odometerKilometres)) {
        this.odometerKilometres = data().deepCopy(fields()[24].schema(), other.odometerKilometres);
        fieldSetFlags()[24] = true;
      }
      if (isValidValue(fields()[25], other.formattedAddress)) {
        this.formattedAddress = data().deepCopy(fields()[25].schema(), other.formattedAddress);
        fieldSetFlags()[25] = true;
      }
      if (isValidValue(fields()[26], other.source)) {
        this.source = data().deepCopy(fields()[26].schema(), other.source);
        fieldSetFlags()[26] = true;
      }
      if (isValidValue(fields()[27], other.avl)) {
        this.avl = data().deepCopy(fields()[27].schema(), other.avl);
        fieldSetFlags()[27] = true;
      }
    }

    /**
      * Gets the value of the 'durableId' field.
      * @return The value.
      */
    public java.lang.CharSequence getDurableId() {
      return durableId;
    }

    /**
      * Sets the value of the 'durableId' field.
      * @param value The value of 'durableId'.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.fact.AvroPosition.Builder setDurableId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.durableId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'durableId' field has been set.
      * @return True if the 'durableId' field has been set, false otherwise.
      */
    public boolean hasDurableId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'durableId' field.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.fact.AvroPosition.Builder clearDurableId() {
      durableId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'ingestedDateUtc' field.
      * @return The value.
      */
    public org.joda.time.DateTime getIngestedDateUtc() {
      return ingestedDateUtc;
    }

    /**
      * Sets the value of the 'ingestedDateUtc' field.
      * @param value The value of 'ingestedDateUtc'.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.fact.AvroPosition.Builder setIngestedDateUtc(org.joda.time.DateTime value) {
      validate(fields()[1], value);
      this.ingestedDateUtc = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'ingestedDateUtc' field has been set.
      * @return True if the 'ingestedDateUtc' field has been set, false otherwise.
      */
    public boolean hasIngestedDateUtc() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'ingestedDateUtc' field.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.fact.AvroPosition.Builder clearIngestedDateUtc() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'subscriptionId' field.
      * @return The value.
      */
    public java.lang.Long getSubscriptionId() {
      return subscriptionId;
    }

    /**
      * Sets the value of the 'subscriptionId' field.
      * @param value The value of 'subscriptionId'.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.fact.AvroPosition.Builder setSubscriptionId(java.lang.Long value) {
      validate(fields()[2], value);
      this.subscriptionId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'subscriptionId' field has been set.
      * @return True if the 'subscriptionId' field has been set, false otherwise.
      */
    public boolean hasSubscriptionId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'subscriptionId' field.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.fact.AvroPosition.Builder clearSubscriptionId() {
      subscriptionId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'lineageCode' field.
      * @return The value.
      */
    public java.lang.Integer getLineageCode() {
      return lineageCode;
    }

    /**
      * Sets the value of the 'lineageCode' field.
      * @param value The value of 'lineageCode'.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.fact.AvroPosition.Builder setLineageCode(java.lang.Integer value) {
      validate(fields()[3], value);
      this.lineageCode = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'lineageCode' field has been set.
      * @return True if the 'lineageCode' field has been set, false otherwise.
      */
    public boolean hasLineageCode() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'lineageCode' field.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.fact.AvroPosition.Builder clearLineageCode() {
      lineageCode = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'driverDurableKey' field.
      * @return The value.
      */
    public java.lang.CharSequence getDriverDurableKey() {
      return driverDurableKey;
    }

    /**
      * Sets the value of the 'driverDurableKey' field.
      * @param value The value of 'driverDurableKey'.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.fact.AvroPosition.Builder setDriverDurableKey(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.driverDurableKey = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'driverDurableKey' field has been set.
      * @return True if the 'driverDurableKey' field has been set, false otherwise.
      */
    public boolean hasDriverDurableKey() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'driverDurableKey' field.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.fact.AvroPosition.Builder clearDriverDurableKey() {
      driverDurableKey = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'vehicleDurableKey' field.
      * @return The value.
      */
    public java.lang.CharSequence getVehicleDurableKey() {
      return vehicleDurableKey;
    }

    /**
      * Sets the value of the 'vehicleDurableKey' field.
      * @param value The value of 'vehicleDurableKey'.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.fact.AvroPosition.Builder setVehicleDurableKey(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.vehicleDurableKey = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'vehicleDurableKey' field has been set.
      * @return True if the 'vehicleDurableKey' field has been set, false otherwise.
      */
    public boolean hasVehicleDurableKey() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'vehicleDurableKey' field.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.fact.AvroPosition.Builder clearVehicleDurableKey() {
      vehicleDurableKey = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'schemaVersion' field.
      * Transport message support: avro schema version number
      * @return The value.
      */
    public java.lang.Integer getSchemaVersion() {
      return schemaVersion;
    }

    /**
      * Sets the value of the 'schemaVersion' field.
      * Transport message support: avro schema version number
      * @param value The value of 'schemaVersion'.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.fact.AvroPosition.Builder setSchemaVersion(java.lang.Integer value) {
      validate(fields()[6], value);
      this.schemaVersion = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'schemaVersion' field has been set.
      * Transport message support: avro schema version number
      * @return True if the 'schemaVersion' field has been set, false otherwise.
      */
    public boolean hasSchemaVersion() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'schemaVersion' field.
      * Transport message support: avro schema version number
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.fact.AvroPosition.Builder clearSchemaVersion() {
      schemaVersion = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'positionId' field.
      * @return The value.
      */
    public java.lang.Long getPositionId() {
      return positionId;
    }

    /**
      * Sets the value of the 'positionId' field.
      * @param value The value of 'positionId'.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.fact.AvroPosition.Builder setPositionId(java.lang.Long value) {
      validate(fields()[7], value);
      this.positionId = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'positionId' field has been set.
      * @return True if the 'positionId' field has been set, false otherwise.
      */
    public boolean hasPositionId() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'positionId' field.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.fact.AvroPosition.Builder clearPositionId() {
      positionId = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'assetId' field.
      * @return The value.
      */
    public java.lang.Long getAssetId() {
      return assetId;
    }

    /**
      * Sets the value of the 'assetId' field.
      * @param value The value of 'assetId'.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.fact.AvroPosition.Builder setAssetId(java.lang.Long value) {
      validate(fields()[8], value);
      this.assetId = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'assetId' field has been set.
      * @return True if the 'assetId' field has been set, false otherwise.
      */
    public boolean hasAssetId() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'assetId' field.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.fact.AvroPosition.Builder clearAssetId() {
      assetId = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'driverId' field.
      * @return The value.
      */
    public java.lang.Long getDriverId() {
      return driverId;
    }

    /**
      * Sets the value of the 'driverId' field.
      * @param value The value of 'driverId'.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.fact.AvroPosition.Builder setDriverId(java.lang.Long value) {
      validate(fields()[9], value);
      this.driverId = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'driverId' field has been set.
      * @return True if the 'driverId' field has been set, false otherwise.
      */
    public boolean hasDriverId() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'driverId' field.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.fact.AvroPosition.Builder clearDriverId() {
      driverId = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * @return The value.
      */
    public org.joda.time.DateTime getTimestamp() {
      return timestamp;
    }

    /**
      * Sets the value of the 'timestamp' field.
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.fact.AvroPosition.Builder setTimestamp(org.joda.time.DateTime value) {
      validate(fields()[10], value);
      this.timestamp = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.fact.AvroPosition.Builder clearTimestamp() {
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'latitude' field.
      * @return The value.
      */
    public java.lang.Double getLatitude() {
      return latitude;
    }

    /**
      * Sets the value of the 'latitude' field.
      * @param value The value of 'latitude'.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.fact.AvroPosition.Builder setLatitude(java.lang.Double value) {
      validate(fields()[11], value);
      this.latitude = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'latitude' field has been set.
      * @return True if the 'latitude' field has been set, false otherwise.
      */
    public boolean hasLatitude() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'latitude' field.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.fact.AvroPosition.Builder clearLatitude() {
      latitude = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'longitude' field.
      * @return The value.
      */
    public java.lang.Double getLongitude() {
      return longitude;
    }

    /**
      * Sets the value of the 'longitude' field.
      * @param value The value of 'longitude'.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.fact.AvroPosition.Builder setLongitude(java.lang.Double value) {
      validate(fields()[12], value);
      this.longitude = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'longitude' field has been set.
      * @return True if the 'longitude' field has been set, false otherwise.
      */
    public boolean hasLongitude() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'longitude' field.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.fact.AvroPosition.Builder clearLongitude() {
      longitude = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
      * Gets the value of the 'speedKilometresPerHour' field.
      * @return The value.
      */
    public java.lang.Double getSpeedKilometresPerHour() {
      return speedKilometresPerHour;
    }

    /**
      * Sets the value of the 'speedKilometresPerHour' field.
      * @param value The value of 'speedKilometresPerHour'.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.fact.AvroPosition.Builder setSpeedKilometresPerHour(java.lang.Double value) {
      validate(fields()[13], value);
      this.speedKilometresPerHour = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /**
      * Checks whether the 'speedKilometresPerHour' field has been set.
      * @return True if the 'speedKilometresPerHour' field has been set, false otherwise.
      */
    public boolean hasSpeedKilometresPerHour() {
      return fieldSetFlags()[13];
    }


    /**
      * Clears the value of the 'speedKilometresPerHour' field.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.fact.AvroPosition.Builder clearSpeedKilometresPerHour() {
      speedKilometresPerHour = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    /**
      * Gets the value of the 'speedLimit' field.
      * @return The value.
      */
    public java.lang.Double getSpeedLimit() {
      return speedLimit;
    }

    /**
      * Sets the value of the 'speedLimit' field.
      * @param value The value of 'speedLimit'.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.fact.AvroPosition.Builder setSpeedLimit(java.lang.Double value) {
      validate(fields()[14], value);
      this.speedLimit = value;
      fieldSetFlags()[14] = true;
      return this;
    }

    /**
      * Checks whether the 'speedLimit' field has been set.
      * @return True if the 'speedLimit' field has been set, false otherwise.
      */
    public boolean hasSpeedLimit() {
      return fieldSetFlags()[14];
    }


    /**
      * Clears the value of the 'speedLimit' field.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.fact.AvroPosition.Builder clearSpeedLimit() {
      speedLimit = null;
      fieldSetFlags()[14] = false;
      return this;
    }

    /**
      * Gets the value of the 'altitudeMetres' field.
      * @return The value.
      */
    public java.lang.Integer getAltitudeMetres() {
      return altitudeMetres;
    }

    /**
      * Sets the value of the 'altitudeMetres' field.
      * @param value The value of 'altitudeMetres'.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.fact.AvroPosition.Builder setAltitudeMetres(java.lang.Integer value) {
      validate(fields()[15], value);
      this.altitudeMetres = value;
      fieldSetFlags()[15] = true;
      return this;
    }

    /**
      * Checks whether the 'altitudeMetres' field has been set.
      * @return True if the 'altitudeMetres' field has been set, false otherwise.
      */
    public boolean hasAltitudeMetres() {
      return fieldSetFlags()[15];
    }


    /**
      * Clears the value of the 'altitudeMetres' field.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.fact.AvroPosition.Builder clearAltitudeMetres() {
      altitudeMetres = null;
      fieldSetFlags()[15] = false;
      return this;
    }

    /**
      * Gets the value of the 'heading' field.
      * @return The value.
      */
    public java.lang.Integer getHeading() {
      return heading;
    }

    /**
      * Sets the value of the 'heading' field.
      * @param value The value of 'heading'.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.fact.AvroPosition.Builder setHeading(java.lang.Integer value) {
      validate(fields()[16], value);
      this.heading = value;
      fieldSetFlags()[16] = true;
      return this;
    }

    /**
      * Checks whether the 'heading' field has been set.
      * @return True if the 'heading' field has been set, false otherwise.
      */
    public boolean hasHeading() {
      return fieldSetFlags()[16];
    }


    /**
      * Clears the value of the 'heading' field.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.fact.AvroPosition.Builder clearHeading() {
      heading = null;
      fieldSetFlags()[16] = false;
      return this;
    }

    /**
      * Gets the value of the 'numberOfSatellites' field.
      * @return The value.
      */
    public java.lang.Integer getNumberOfSatellites() {
      return numberOfSatellites;
    }

    /**
      * Sets the value of the 'numberOfSatellites' field.
      * @param value The value of 'numberOfSatellites'.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.fact.AvroPosition.Builder setNumberOfSatellites(java.lang.Integer value) {
      validate(fields()[17], value);
      this.numberOfSatellites = value;
      fieldSetFlags()[17] = true;
      return this;
    }

    /**
      * Checks whether the 'numberOfSatellites' field has been set.
      * @return True if the 'numberOfSatellites' field has been set, false otherwise.
      */
    public boolean hasNumberOfSatellites() {
      return fieldSetFlags()[17];
    }


    /**
      * Clears the value of the 'numberOfSatellites' field.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.fact.AvroPosition.Builder clearNumberOfSatellites() {
      numberOfSatellites = null;
      fieldSetFlags()[17] = false;
      return this;
    }

    /**
      * Gets the value of the 'hdop' field.
      * @return The value.
      */
    public java.lang.Integer getHdop() {
      return hdop;
    }

    /**
      * Sets the value of the 'hdop' field.
      * @param value The value of 'hdop'.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.fact.AvroPosition.Builder setHdop(java.lang.Integer value) {
      validate(fields()[18], value);
      this.hdop = value;
      fieldSetFlags()[18] = true;
      return this;
    }

    /**
      * Checks whether the 'hdop' field has been set.
      * @return True if the 'hdop' field has been set, false otherwise.
      */
    public boolean hasHdop() {
      return fieldSetFlags()[18];
    }


    /**
      * Clears the value of the 'hdop' field.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.fact.AvroPosition.Builder clearHdop() {
      hdop = null;
      fieldSetFlags()[18] = false;
      return this;
    }

    /**
      * Gets the value of the 'vdop' field.
      * @return The value.
      */
    public java.lang.Integer getVdop() {
      return vdop;
    }

    /**
      * Sets the value of the 'vdop' field.
      * @param value The value of 'vdop'.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.fact.AvroPosition.Builder setVdop(java.lang.Integer value) {
      validate(fields()[19], value);
      this.vdop = value;
      fieldSetFlags()[19] = true;
      return this;
    }

    /**
      * Checks whether the 'vdop' field has been set.
      * @return True if the 'vdop' field has been set, false otherwise.
      */
    public boolean hasVdop() {
      return fieldSetFlags()[19];
    }


    /**
      * Clears the value of the 'vdop' field.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.fact.AvroPosition.Builder clearVdop() {
      vdop = null;
      fieldSetFlags()[19] = false;
      return this;
    }

    /**
      * Gets the value of the 'pdop' field.
      * @return The value.
      */
    public java.lang.Integer getPdop() {
      return pdop;
    }

    /**
      * Sets the value of the 'pdop' field.
      * @param value The value of 'pdop'.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.fact.AvroPosition.Builder setPdop(java.lang.Integer value) {
      validate(fields()[20], value);
      this.pdop = value;
      fieldSetFlags()[20] = true;
      return this;
    }

    /**
      * Checks whether the 'pdop' field has been set.
      * @return True if the 'pdop' field has been set, false otherwise.
      */
    public boolean hasPdop() {
      return fieldSetFlags()[20];
    }


    /**
      * Clears the value of the 'pdop' field.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.fact.AvroPosition.Builder clearPdop() {
      pdop = null;
      fieldSetFlags()[20] = false;
      return this;
    }

    /**
      * Gets the value of the 'ageOfReadingSeconds' field.
      * @return The value.
      */
    public java.lang.Long getAgeOfReadingSeconds() {
      return ageOfReadingSeconds;
    }

    /**
      * Sets the value of the 'ageOfReadingSeconds' field.
      * @param value The value of 'ageOfReadingSeconds'.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.fact.AvroPosition.Builder setAgeOfReadingSeconds(java.lang.Long value) {
      validate(fields()[21], value);
      this.ageOfReadingSeconds = value;
      fieldSetFlags()[21] = true;
      return this;
    }

    /**
      * Checks whether the 'ageOfReadingSeconds' field has been set.
      * @return True if the 'ageOfReadingSeconds' field has been set, false otherwise.
      */
    public boolean hasAgeOfReadingSeconds() {
      return fieldSetFlags()[21];
    }


    /**
      * Clears the value of the 'ageOfReadingSeconds' field.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.fact.AvroPosition.Builder clearAgeOfReadingSeconds() {
      ageOfReadingSeconds = null;
      fieldSetFlags()[21] = false;
      return this;
    }

    /**
      * Gets the value of the 'distanceSinceReadingKilometres' field.
      * @return The value.
      */
    public java.lang.Integer getDistanceSinceReadingKilometres() {
      return distanceSinceReadingKilometres;
    }

    /**
      * Sets the value of the 'distanceSinceReadingKilometres' field.
      * @param value The value of 'distanceSinceReadingKilometres'.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.fact.AvroPosition.Builder setDistanceSinceReadingKilometres(java.lang.Integer value) {
      validate(fields()[22], value);
      this.distanceSinceReadingKilometres = value;
      fieldSetFlags()[22] = true;
      return this;
    }

    /**
      * Checks whether the 'distanceSinceReadingKilometres' field has been set.
      * @return True if the 'distanceSinceReadingKilometres' field has been set, false otherwise.
      */
    public boolean hasDistanceSinceReadingKilometres() {
      return fieldSetFlags()[22];
    }


    /**
      * Clears the value of the 'distanceSinceReadingKilometres' field.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.fact.AvroPosition.Builder clearDistanceSinceReadingKilometres() {
      distanceSinceReadingKilometres = null;
      fieldSetFlags()[22] = false;
      return this;
    }

    /**
      * Gets the value of the 'ignitionOn' field.
      * @return The value.
      */
    public java.lang.Boolean getIgnitionOn() {
      return ignitionOn;
    }

    /**
      * Sets the value of the 'ignitionOn' field.
      * @param value The value of 'ignitionOn'.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.fact.AvroPosition.Builder setIgnitionOn(java.lang.Boolean value) {
      validate(fields()[23], value);
      this.ignitionOn = value;
      fieldSetFlags()[23] = true;
      return this;
    }

    /**
      * Checks whether the 'ignitionOn' field has been set.
      * @return True if the 'ignitionOn' field has been set, false otherwise.
      */
    public boolean hasIgnitionOn() {
      return fieldSetFlags()[23];
    }


    /**
      * Clears the value of the 'ignitionOn' field.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.fact.AvroPosition.Builder clearIgnitionOn() {
      ignitionOn = null;
      fieldSetFlags()[23] = false;
      return this;
    }

    /**
      * Gets the value of the 'odometerKilometres' field.
      * @return The value.
      */
    public java.lang.Double getOdometerKilometres() {
      return odometerKilometres;
    }

    /**
      * Sets the value of the 'odometerKilometres' field.
      * @param value The value of 'odometerKilometres'.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.fact.AvroPosition.Builder setOdometerKilometres(java.lang.Double value) {
      validate(fields()[24], value);
      this.odometerKilometres = value;
      fieldSetFlags()[24] = true;
      return this;
    }

    /**
      * Checks whether the 'odometerKilometres' field has been set.
      * @return True if the 'odometerKilometres' field has been set, false otherwise.
      */
    public boolean hasOdometerKilometres() {
      return fieldSetFlags()[24];
    }


    /**
      * Clears the value of the 'odometerKilometres' field.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.fact.AvroPosition.Builder clearOdometerKilometres() {
      odometerKilometres = null;
      fieldSetFlags()[24] = false;
      return this;
    }

    /**
      * Gets the value of the 'formattedAddress' field.
      * @return The value.
      */
    public java.lang.CharSequence getFormattedAddress() {
      return formattedAddress;
    }

    /**
      * Sets the value of the 'formattedAddress' field.
      * @param value The value of 'formattedAddress'.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.fact.AvroPosition.Builder setFormattedAddress(java.lang.CharSequence value) {
      validate(fields()[25], value);
      this.formattedAddress = value;
      fieldSetFlags()[25] = true;
      return this;
    }

    /**
      * Checks whether the 'formattedAddress' field has been set.
      * @return True if the 'formattedAddress' field has been set, false otherwise.
      */
    public boolean hasFormattedAddress() {
      return fieldSetFlags()[25];
    }


    /**
      * Clears the value of the 'formattedAddress' field.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.fact.AvroPosition.Builder clearFormattedAddress() {
      formattedAddress = null;
      fieldSetFlags()[25] = false;
      return this;
    }

    /**
      * Gets the value of the 'source' field.
      * @return The value.
      */
    public java.lang.CharSequence getSource() {
      return source;
    }

    /**
      * Sets the value of the 'source' field.
      * @param value The value of 'source'.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.fact.AvroPosition.Builder setSource(java.lang.CharSequence value) {
      validate(fields()[26], value);
      this.source = value;
      fieldSetFlags()[26] = true;
      return this;
    }

    /**
      * Checks whether the 'source' field has been set.
      * @return True if the 'source' field has been set, false otherwise.
      */
    public boolean hasSource() {
      return fieldSetFlags()[26];
    }


    /**
      * Clears the value of the 'source' field.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.fact.AvroPosition.Builder clearSource() {
      source = null;
      fieldSetFlags()[26] = false;
      return this;
    }

    /**
      * Gets the value of the 'avl' field.
      * @return The value.
      */
    public java.lang.Boolean getAvl() {
      return avl;
    }

    /**
      * Sets the value of the 'avl' field.
      * @param value The value of 'avl'.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.fact.AvroPosition.Builder setAvl(java.lang.Boolean value) {
      validate(fields()[27], value);
      this.avl = value;
      fieldSetFlags()[27] = true;
      return this;
    }

    /**
      * Checks whether the 'avl' field has been set.
      * @return True if the 'avl' field has been set, false otherwise.
      */
    public boolean hasAvl() {
      return fieldSetFlags()[27];
    }


    /**
      * Clears the value of the 'avl' field.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.fact.AvroPosition.Builder clearAvl() {
      avl = null;
      fieldSetFlags()[27] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AvroPosition build() {
      try {
        AvroPosition record = new AvroPosition();
        record.durableId = fieldSetFlags()[0] ? this.durableId : (java.lang.CharSequence) defaultValue(fields()[0], record.getConversion(0));
        record.ingestedDateUtc = fieldSetFlags()[1] ? this.ingestedDateUtc : (org.joda.time.DateTime) defaultValue(fields()[1], record.getConversion(1));
        record.subscriptionId = fieldSetFlags()[2] ? this.subscriptionId : (java.lang.Long) defaultValue(fields()[2], record.getConversion(2));
        record.lineageCode = fieldSetFlags()[3] ? this.lineageCode : (java.lang.Integer) defaultValue(fields()[3], record.getConversion(3));
        record.driverDurableKey = fieldSetFlags()[4] ? this.driverDurableKey : (java.lang.CharSequence) defaultValue(fields()[4], record.getConversion(4));
        record.vehicleDurableKey = fieldSetFlags()[5] ? this.vehicleDurableKey : (java.lang.CharSequence) defaultValue(fields()[5], record.getConversion(5));
        record.schemaVersion = fieldSetFlags()[6] ? this.schemaVersion : (java.lang.Integer) defaultValue(fields()[6], record.getConversion(6));
        record.positionId = fieldSetFlags()[7] ? this.positionId : (java.lang.Long) defaultValue(fields()[7], record.getConversion(7));
        record.assetId = fieldSetFlags()[8] ? this.assetId : (java.lang.Long) defaultValue(fields()[8], record.getConversion(8));
        record.driverId = fieldSetFlags()[9] ? this.driverId : (java.lang.Long) defaultValue(fields()[9], record.getConversion(9));
        record.timestamp = fieldSetFlags()[10] ? this.timestamp : (org.joda.time.DateTime) defaultValue(fields()[10], record.getConversion(10));
        record.latitude = fieldSetFlags()[11] ? this.latitude : (java.lang.Double) defaultValue(fields()[11], record.getConversion(11));
        record.longitude = fieldSetFlags()[12] ? this.longitude : (java.lang.Double) defaultValue(fields()[12], record.getConversion(12));
        record.speedKilometresPerHour = fieldSetFlags()[13] ? this.speedKilometresPerHour : (java.lang.Double) defaultValue(fields()[13], record.getConversion(13));
        record.speedLimit = fieldSetFlags()[14] ? this.speedLimit : (java.lang.Double) defaultValue(fields()[14], record.getConversion(14));
        record.altitudeMetres = fieldSetFlags()[15] ? this.altitudeMetres : (java.lang.Integer) defaultValue(fields()[15], record.getConversion(15));
        record.heading = fieldSetFlags()[16] ? this.heading : (java.lang.Integer) defaultValue(fields()[16], record.getConversion(16));
        record.numberOfSatellites = fieldSetFlags()[17] ? this.numberOfSatellites : (java.lang.Integer) defaultValue(fields()[17], record.getConversion(17));
        record.hdop = fieldSetFlags()[18] ? this.hdop : (java.lang.Integer) defaultValue(fields()[18], record.getConversion(18));
        record.vdop = fieldSetFlags()[19] ? this.vdop : (java.lang.Integer) defaultValue(fields()[19], record.getConversion(19));
        record.pdop = fieldSetFlags()[20] ? this.pdop : (java.lang.Integer) defaultValue(fields()[20], record.getConversion(20));
        record.ageOfReadingSeconds = fieldSetFlags()[21] ? this.ageOfReadingSeconds : (java.lang.Long) defaultValue(fields()[21], record.getConversion(21));
        record.distanceSinceReadingKilometres = fieldSetFlags()[22] ? this.distanceSinceReadingKilometres : (java.lang.Integer) defaultValue(fields()[22], record.getConversion(22));
        record.ignitionOn = fieldSetFlags()[23] ? this.ignitionOn : (java.lang.Boolean) defaultValue(fields()[23], record.getConversion(23));
        record.odometerKilometres = fieldSetFlags()[24] ? this.odometerKilometres : (java.lang.Double) defaultValue(fields()[24], record.getConversion(24));
        record.formattedAddress = fieldSetFlags()[25] ? this.formattedAddress : (java.lang.CharSequence) defaultValue(fields()[25], record.getConversion(25));
        record.source = fieldSetFlags()[26] ? this.source : (java.lang.CharSequence) defaultValue(fields()[26], record.getConversion(26));
        record.avl = fieldSetFlags()[27] ? this.avl : (java.lang.Boolean) defaultValue(fields()[27], record.getConversion(27));
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AvroPosition>
    WRITER$ = (org.apache.avro.io.DatumWriter<AvroPosition>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AvroPosition>
    READER$ = (org.apache.avro.io.DatumReader<AvroPosition>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
