dummy=dummy_value
Secret-Sql-PUMPS-user=value-Sql-PUMPS-user
Secret-Sql-PUMPS-password=value-Sql-PUMPS-password
Secret-Sql-MDM-user=value-Sql-MDM-user
Secret-Sql-MDM-password=value-Sql-MDM-password
Secret-Sql-SPEEDLAYER-user=value-Sql-SPEEDLAYER-user
Secret-Sql-SPEEDLAYER-password=value-Sql-PUMPS-password
# the following two lines must be commented for test purpose
#Secret-Hive-RAW-key=value-Hive-RAW-key
#Secret-Hive-RAW-connect=value-Hive-RAW-connect
Secret-Hive-PREPARED-key=value-Hive-PREPARED-key
Secret-Hive-PREPARED-connect=value-Hive-PREPARED-connect]

Secret-Mix-COMMON-clientId=value-Mix-COMMON-clientId
Secret-Mix-COMMON-clientSecret=value-Mix-COMMON-clientSecret
Secret-Mix-ACCOUNT-name-vadim-volkov=vadim-volkov-secret
Secret-Mix-ACCOUNT-name-nikita-poberezkin=nikita-poberezkin-secret
Secret-Mix-ACCOUNT-name-alexander-kochurin=alexander-kochurin-secret


