{
    "type": "record",
    "name": "AvroPosition",
    "namespace": "com.epam.tcodata.models.avro.fact",
    "fields": [
	    {
            "name": "durableId",
            "type": ["null", "string"]
        },
	    {
            "name": "ingestedDateUtc",
            "type": {"type": "long", "logicalType": "timestamp-millis"}
        },
	    {
            "name": "subscriptionId",
            "type": ["null", "long"]
        },
	    {
            "name": "lineageCode",
            "type": ["null", "int"]
        },
	    {
            "name": "driverDurableKey",
            "type": ["null", "string"]
        },
	    {
            "name": "vehicleDurableKey",
            "type": ["null", "string"]
        },
	    {
            "name": "schemaVersion",
            "doc": "Transport message support: avro schema version number",
            "type": ["null", "int"]
        },
        {
            "name": "positionId",
            "type": ["null", "long"]
        },
        {
            "name": "assetId",
            "type": ["null", "long"]
        },
        {
            "name": "driverId",
            "type": ["null", "long"]
        },
        {
            "name": "timestamp",
            "type": {"type": "long", "logicalType": "timestamp-millis"}
        },
        {
            "name": "latitude",
            "type": ["null", "double"]
        },
        {
            "name": "longitude",
            "type": ["null", "double"]
        },
        {
            "name": "speedKilometresPerHour",
            "type": ["null", "double"]
        },
        {
            "name": "speedLimit",
            "type": ["null", "double"]
        },
        {
            "name": "altitudeMetres",
            "type": ["null", "int"]
        },
        {
            "name": "heading",
            "type": ["null", "int"]
        },
        {
            "name": "numberOfSatellites",
            "type": ["null", "int"]
        },
	    {
            "name": "hdop",
            "type": ["null", "int"]
        },
        {
            "name": "vdop",
            "type": ["null", "int"]
        },
        {
            "name": "pdop",
            "type": ["null", "int"]
        },
        {
            "name": "ageOfReadingSeconds",
            "type": ["null", "long"]
        },
        {
            "name": "distanceSinceReadingKilometres",
            "type": ["null", "int"]
        },
        {
            "name": "ignitionOn",
            "type": ["null", "boolean"]
        },
        {
            "name": "odometerKilometres",
            "type": ["null", "double"]
        },
        {
            "name": "formattedAddress",
            "type": ["null", "string"]
        },
        {
            "name": "source",
            "type": ["null", "string"]
        },
        {
            "name": "avl",
            "type": ["null", "boolean"]
        }
    ]
}
