{
    "type": "record",
    "name": "AvroDriver",
    "namespace": "com.epam.tcodata.models.avro.dimension",
    "fields": [
	    {
            "name": "durableId",
            "type": ["null", "string"]
        },
	    {
            "name": "ingestedDateUtc",
            "type": {"type": "long", "logicalType": "timestamp-millis"}
        },
	    {
            "name": "subscriptionId",
            "type": ["null", "long"]
        },
	    {
            "name": "lineageCode",
            "type": ["null", "int"]
        },
	    {
            "name": "schemaVersion",
            "doc": "Transport message support: avro schema version number",
            "type": ["null", "int"]
        },
        {
            "name": "siteId",
            "type": ["null", "long"]
        },
        {
            "name": "driverId",
            "type": ["null", "long"]
        },
        {
            "name": "name",
            "type": ["null", "string"]
        },
        {
            "name": "imageUri",
            "type": ["null", "string"]
        },
        {
            "name": "fmDriverId",
            "type": ["null", "long"]
        },
        {
            "name": "employeeNumber",
            "type": ["null", "string"]
        },
        {
            "name": "systemDriver",
            "type": ["null", "boolean"]
        },
        {
            "name": "mobileNumber",
            "type": ["null", "string"]
        },
        {
            "name": "email",
            "type": ["null", "string"]
        },
        {
            "name": "extendedDriverId",
            "type": ["null", "string"]
        },
	    {
            "name": "extendedDriverIdType",
            "type": ["null", "string"]
        },
        {
            "name": "country",
            "type": ["null", "string"]
        }
    ]
}
