/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.epam.tcodata.models.avro.dimension;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class AvroDriver extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3074134864353088084L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AvroDriver\",\"namespace\":\"com.epam.tcodata.models.avro.dimension\",\"fields\":[{\"name\":\"durableId\",\"type\":[\"null\",\"string\"]},{\"name\":\"ingestedDateUtc\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}},{\"name\":\"subscriptionId\",\"type\":[\"null\",\"long\"]},{\"name\":\"lineageCode\",\"type\":[\"null\",\"int\"]},{\"name\":\"schemaVersion\",\"type\":[\"null\",\"int\"],\"doc\":\"Transport message support: avro schema version number\"},{\"name\":\"siteId\",\"type\":[\"null\",\"long\"]},{\"name\":\"driverId\",\"type\":[\"null\",\"long\"]},{\"name\":\"name\",\"type\":[\"null\",\"string\"]},{\"name\":\"imageUri\",\"type\":[\"null\",\"string\"]},{\"name\":\"fmDriverId\",\"type\":[\"null\",\"long\"]},{\"name\":\"employeeNumber\",\"type\":[\"null\",\"string\"]},{\"name\":\"systemDriver\",\"type\":[\"null\",\"boolean\"]},{\"name\":\"mobileNumber\",\"type\":[\"null\",\"string\"]},{\"name\":\"email\",\"type\":[\"null\",\"string\"]},{\"name\":\"extendedDriverId\",\"type\":[\"null\",\"string\"]},{\"name\":\"extendedDriverIdType\",\"type\":[\"null\",\"string\"]},{\"name\":\"country\",\"type\":[\"null\",\"string\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AvroDriver> ENCODER =
      new BinaryMessageEncoder<AvroDriver>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AvroDriver> DECODER =
      new BinaryMessageDecoder<AvroDriver>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<AvroDriver> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<AvroDriver> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<AvroDriver>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this AvroDriver to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a AvroDriver from a ByteBuffer. */
  public static AvroDriver fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence durableId;
  @Deprecated public org.joda.time.DateTime ingestedDateUtc;
  @Deprecated public java.lang.Long subscriptionId;
  @Deprecated public java.lang.Integer lineageCode;
  /** Transport message support: avro schema version number */
  @Deprecated public java.lang.Integer schemaVersion;
  @Deprecated public java.lang.Long siteId;
  @Deprecated public java.lang.Long driverId;
  @Deprecated public java.lang.CharSequence name;
  @Deprecated public java.lang.CharSequence imageUri;
  @Deprecated public java.lang.Long fmDriverId;
  @Deprecated public java.lang.CharSequence employeeNumber;
  @Deprecated public java.lang.Boolean systemDriver;
  @Deprecated public java.lang.CharSequence mobileNumber;
  @Deprecated public java.lang.CharSequence email;
  @Deprecated public java.lang.CharSequence extendedDriverId;
  @Deprecated public java.lang.CharSequence extendedDriverIdType;
  @Deprecated public java.lang.CharSequence country;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AvroDriver() {}

  /**
   * All-args constructor.
   * @param durableId The new value for durableId
   * @param ingestedDateUtc The new value for ingestedDateUtc
   * @param subscriptionId The new value for subscriptionId
   * @param lineageCode The new value for lineageCode
   * @param schemaVersion Transport message support: avro schema version number
   * @param siteId The new value for siteId
   * @param driverId The new value for driverId
   * @param name The new value for name
   * @param imageUri The new value for imageUri
   * @param fmDriverId The new value for fmDriverId
   * @param employeeNumber The new value for employeeNumber
   * @param systemDriver The new value for systemDriver
   * @param mobileNumber The new value for mobileNumber
   * @param email The new value for email
   * @param extendedDriverId The new value for extendedDriverId
   * @param extendedDriverIdType The new value for extendedDriverIdType
   * @param country The new value for country
   */
  public AvroDriver(java.lang.CharSequence durableId, org.joda.time.DateTime ingestedDateUtc, java.lang.Long subscriptionId, java.lang.Integer lineageCode, java.lang.Integer schemaVersion, java.lang.Long siteId, java.lang.Long driverId, java.lang.CharSequence name, java.lang.CharSequence imageUri, java.lang.Long fmDriverId, java.lang.CharSequence employeeNumber, java.lang.Boolean systemDriver, java.lang.CharSequence mobileNumber, java.lang.CharSequence email, java.lang.CharSequence extendedDriverId, java.lang.CharSequence extendedDriverIdType, java.lang.CharSequence country) {
    this.durableId = durableId;
    this.ingestedDateUtc = ingestedDateUtc;
    this.subscriptionId = subscriptionId;
    this.lineageCode = lineageCode;
    this.schemaVersion = schemaVersion;
    this.siteId = siteId;
    this.driverId = driverId;
    this.name = name;
    this.imageUri = imageUri;
    this.fmDriverId = fmDriverId;
    this.employeeNumber = employeeNumber;
    this.systemDriver = systemDriver;
    this.mobileNumber = mobileNumber;
    this.email = email;
    this.extendedDriverId = extendedDriverId;
    this.extendedDriverIdType = extendedDriverIdType;
    this.country = country;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return durableId;
    case 1: return ingestedDateUtc;
    case 2: return subscriptionId;
    case 3: return lineageCode;
    case 4: return schemaVersion;
    case 5: return siteId;
    case 6: return driverId;
    case 7: return name;
    case 8: return imageUri;
    case 9: return fmDriverId;
    case 10: return employeeNumber;
    case 11: return systemDriver;
    case 12: return mobileNumber;
    case 13: return email;
    case 14: return extendedDriverId;
    case 15: return extendedDriverIdType;
    case 16: return country;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  protected static final org.apache.avro.data.TimeConversions.DateConversion DATE_CONVERSION = new org.apache.avro.data.TimeConversions.DateConversion();
  protected static final org.apache.avro.data.TimeConversions.TimeConversion TIME_CONVERSION = new org.apache.avro.data.TimeConversions.TimeConversion();
  protected static final org.apache.avro.data.TimeConversions.TimestampConversion TIMESTAMP_CONVERSION = new org.apache.avro.data.TimeConversions.TimestampConversion();
  protected static final org.apache.avro.Conversions.DecimalConversion DECIMAL_CONVERSION = new org.apache.avro.Conversions.DecimalConversion();

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      TIMESTAMP_CONVERSION,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: durableId = (java.lang.CharSequence)value$; break;
    case 1: ingestedDateUtc = (org.joda.time.DateTime)value$; break;
    case 2: subscriptionId = (java.lang.Long)value$; break;
    case 3: lineageCode = (java.lang.Integer)value$; break;
    case 4: schemaVersion = (java.lang.Integer)value$; break;
    case 5: siteId = (java.lang.Long)value$; break;
    case 6: driverId = (java.lang.Long)value$; break;
    case 7: name = (java.lang.CharSequence)value$; break;
    case 8: imageUri = (java.lang.CharSequence)value$; break;
    case 9: fmDriverId = (java.lang.Long)value$; break;
    case 10: employeeNumber = (java.lang.CharSequence)value$; break;
    case 11: systemDriver = (java.lang.Boolean)value$; break;
    case 12: mobileNumber = (java.lang.CharSequence)value$; break;
    case 13: email = (java.lang.CharSequence)value$; break;
    case 14: extendedDriverId = (java.lang.CharSequence)value$; break;
    case 15: extendedDriverIdType = (java.lang.CharSequence)value$; break;
    case 16: country = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'durableId' field.
   * @return The value of the 'durableId' field.
   */
  public java.lang.CharSequence getDurableId() {
    return durableId;
  }

  /**
   * Sets the value of the 'durableId' field.
   * @param value the value to set.
   */
  public void setDurableId(java.lang.CharSequence value) {
    this.durableId = value;
  }

  /**
   * Gets the value of the 'ingestedDateUtc' field.
   * @return The value of the 'ingestedDateUtc' field.
   */
  public org.joda.time.DateTime getIngestedDateUtc() {
    return ingestedDateUtc;
  }

  /**
   * Sets the value of the 'ingestedDateUtc' field.
   * @param value the value to set.
   */
  public void setIngestedDateUtc(org.joda.time.DateTime value) {
    this.ingestedDateUtc = value;
  }

  /**
   * Gets the value of the 'subscriptionId' field.
   * @return The value of the 'subscriptionId' field.
   */
  public java.lang.Long getSubscriptionId() {
    return subscriptionId;
  }

  /**
   * Sets the value of the 'subscriptionId' field.
   * @param value the value to set.
   */
  public void setSubscriptionId(java.lang.Long value) {
    this.subscriptionId = value;
  }

  /**
   * Gets the value of the 'lineageCode' field.
   * @return The value of the 'lineageCode' field.
   */
  public java.lang.Integer getLineageCode() {
    return lineageCode;
  }

  /**
   * Sets the value of the 'lineageCode' field.
   * @param value the value to set.
   */
  public void setLineageCode(java.lang.Integer value) {
    this.lineageCode = value;
  }

  /**
   * Gets the value of the 'schemaVersion' field.
   * @return Transport message support: avro schema version number
   */
  public java.lang.Integer getSchemaVersion() {
    return schemaVersion;
  }

  /**
   * Sets the value of the 'schemaVersion' field.
   * Transport message support: avro schema version number
   * @param value the value to set.
   */
  public void setSchemaVersion(java.lang.Integer value) {
    this.schemaVersion = value;
  }

  /**
   * Gets the value of the 'siteId' field.
   * @return The value of the 'siteId' field.
   */
  public java.lang.Long getSiteId() {
    return siteId;
  }

  /**
   * Sets the value of the 'siteId' field.
   * @param value the value to set.
   */
  public void setSiteId(java.lang.Long value) {
    this.siteId = value;
  }

  /**
   * Gets the value of the 'driverId' field.
   * @return The value of the 'driverId' field.
   */
  public java.lang.Long getDriverId() {
    return driverId;
  }

  /**
   * Sets the value of the 'driverId' field.
   * @param value the value to set.
   */
  public void setDriverId(java.lang.Long value) {
    this.driverId = value;
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'imageUri' field.
   * @return The value of the 'imageUri' field.
   */
  public java.lang.CharSequence getImageUri() {
    return imageUri;
  }

  /**
   * Sets the value of the 'imageUri' field.
   * @param value the value to set.
   */
  public void setImageUri(java.lang.CharSequence value) {
    this.imageUri = value;
  }

  /**
   * Gets the value of the 'fmDriverId' field.
   * @return The value of the 'fmDriverId' field.
   */
  public java.lang.Long getFmDriverId() {
    return fmDriverId;
  }

  /**
   * Sets the value of the 'fmDriverId' field.
   * @param value the value to set.
   */
  public void setFmDriverId(java.lang.Long value) {
    this.fmDriverId = value;
  }

  /**
   * Gets the value of the 'employeeNumber' field.
   * @return The value of the 'employeeNumber' field.
   */
  public java.lang.CharSequence getEmployeeNumber() {
    return employeeNumber;
  }

  /**
   * Sets the value of the 'employeeNumber' field.
   * @param value the value to set.
   */
  public void setEmployeeNumber(java.lang.CharSequence value) {
    this.employeeNumber = value;
  }

  /**
   * Gets the value of the 'systemDriver' field.
   * @return The value of the 'systemDriver' field.
   */
  public java.lang.Boolean getSystemDriver() {
    return systemDriver;
  }

  /**
   * Sets the value of the 'systemDriver' field.
   * @param value the value to set.
   */
  public void setSystemDriver(java.lang.Boolean value) {
    this.systemDriver = value;
  }

  /**
   * Gets the value of the 'mobileNumber' field.
   * @return The value of the 'mobileNumber' field.
   */
  public java.lang.CharSequence getMobileNumber() {
    return mobileNumber;
  }

  /**
   * Sets the value of the 'mobileNumber' field.
   * @param value the value to set.
   */
  public void setMobileNumber(java.lang.CharSequence value) {
    this.mobileNumber = value;
  }

  /**
   * Gets the value of the 'email' field.
   * @return The value of the 'email' field.
   */
  public java.lang.CharSequence getEmail() {
    return email;
  }

  /**
   * Sets the value of the 'email' field.
   * @param value the value to set.
   */
  public void setEmail(java.lang.CharSequence value) {
    this.email = value;
  }

  /**
   * Gets the value of the 'extendedDriverId' field.
   * @return The value of the 'extendedDriverId' field.
   */
  public java.lang.CharSequence getExtendedDriverId() {
    return extendedDriverId;
  }

  /**
   * Sets the value of the 'extendedDriverId' field.
   * @param value the value to set.
   */
  public void setExtendedDriverId(java.lang.CharSequence value) {
    this.extendedDriverId = value;
  }

  /**
   * Gets the value of the 'extendedDriverIdType' field.
   * @return The value of the 'extendedDriverIdType' field.
   */
  public java.lang.CharSequence getExtendedDriverIdType() {
    return extendedDriverIdType;
  }

  /**
   * Sets the value of the 'extendedDriverIdType' field.
   * @param value the value to set.
   */
  public void setExtendedDriverIdType(java.lang.CharSequence value) {
    this.extendedDriverIdType = value;
  }

  /**
   * Gets the value of the 'country' field.
   * @return The value of the 'country' field.
   */
  public java.lang.CharSequence getCountry() {
    return country;
  }

  /**
   * Sets the value of the 'country' field.
   * @param value the value to set.
   */
  public void setCountry(java.lang.CharSequence value) {
    this.country = value;
  }

  /**
   * Creates a new AvroDriver RecordBuilder.
   * @return A new AvroDriver RecordBuilder
   */
  public static com.epam.tcodata.models.avro.dimension.AvroDriver.Builder newBuilder() {
    return new com.epam.tcodata.models.avro.dimension.AvroDriver.Builder();
  }

  /**
   * Creates a new AvroDriver RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AvroDriver RecordBuilder
   */
  public static com.epam.tcodata.models.avro.dimension.AvroDriver.Builder newBuilder(com.epam.tcodata.models.avro.dimension.AvroDriver.Builder other) {
    return new com.epam.tcodata.models.avro.dimension.AvroDriver.Builder(other);
  }

  /**
   * Creates a new AvroDriver RecordBuilder by copying an existing AvroDriver instance.
   * @param other The existing instance to copy.
   * @return A new AvroDriver RecordBuilder
   */
  public static com.epam.tcodata.models.avro.dimension.AvroDriver.Builder newBuilder(com.epam.tcodata.models.avro.dimension.AvroDriver other) {
    return new com.epam.tcodata.models.avro.dimension.AvroDriver.Builder(other);
  }

  /**
   * RecordBuilder for AvroDriver instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AvroDriver>
    implements org.apache.avro.data.RecordBuilder<AvroDriver> {

    private java.lang.CharSequence durableId;
    private org.joda.time.DateTime ingestedDateUtc;
    private java.lang.Long subscriptionId;
    private java.lang.Integer lineageCode;
    /** Transport message support: avro schema version number */
    private java.lang.Integer schemaVersion;
    private java.lang.Long siteId;
    private java.lang.Long driverId;
    private java.lang.CharSequence name;
    private java.lang.CharSequence imageUri;
    private java.lang.Long fmDriverId;
    private java.lang.CharSequence employeeNumber;
    private java.lang.Boolean systemDriver;
    private java.lang.CharSequence mobileNumber;
    private java.lang.CharSequence email;
    private java.lang.CharSequence extendedDriverId;
    private java.lang.CharSequence extendedDriverIdType;
    private java.lang.CharSequence country;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.epam.tcodata.models.avro.dimension.AvroDriver.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.durableId)) {
        this.durableId = data().deepCopy(fields()[0].schema(), other.durableId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.ingestedDateUtc)) {
        this.ingestedDateUtc = data().deepCopy(fields()[1].schema(), other.ingestedDateUtc);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.subscriptionId)) {
        this.subscriptionId = data().deepCopy(fields()[2].schema(), other.subscriptionId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.lineageCode)) {
        this.lineageCode = data().deepCopy(fields()[3].schema(), other.lineageCode);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.schemaVersion)) {
        this.schemaVersion = data().deepCopy(fields()[4].schema(), other.schemaVersion);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.siteId)) {
        this.siteId = data().deepCopy(fields()[5].schema(), other.siteId);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.driverId)) {
        this.driverId = data().deepCopy(fields()[6].schema(), other.driverId);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.name)) {
        this.name = data().deepCopy(fields()[7].schema(), other.name);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.imageUri)) {
        this.imageUri = data().deepCopy(fields()[8].schema(), other.imageUri);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.fmDriverId)) {
        this.fmDriverId = data().deepCopy(fields()[9].schema(), other.fmDriverId);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.employeeNumber)) {
        this.employeeNumber = data().deepCopy(fields()[10].schema(), other.employeeNumber);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.systemDriver)) {
        this.systemDriver = data().deepCopy(fields()[11].schema(), other.systemDriver);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.mobileNumber)) {
        this.mobileNumber = data().deepCopy(fields()[12].schema(), other.mobileNumber);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.email)) {
        this.email = data().deepCopy(fields()[13].schema(), other.email);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.extendedDriverId)) {
        this.extendedDriverId = data().deepCopy(fields()[14].schema(), other.extendedDriverId);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.extendedDriverIdType)) {
        this.extendedDriverIdType = data().deepCopy(fields()[15].schema(), other.extendedDriverIdType);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.country)) {
        this.country = data().deepCopy(fields()[16].schema(), other.country);
        fieldSetFlags()[16] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing AvroDriver instance
     * @param other The existing instance to copy.
     */
    private Builder(com.epam.tcodata.models.avro.dimension.AvroDriver other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.durableId)) {
        this.durableId = data().deepCopy(fields()[0].schema(), other.durableId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.ingestedDateUtc)) {
        this.ingestedDateUtc = data().deepCopy(fields()[1].schema(), other.ingestedDateUtc);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.subscriptionId)) {
        this.subscriptionId = data().deepCopy(fields()[2].schema(), other.subscriptionId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.lineageCode)) {
        this.lineageCode = data().deepCopy(fields()[3].schema(), other.lineageCode);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.schemaVersion)) {
        this.schemaVersion = data().deepCopy(fields()[4].schema(), other.schemaVersion);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.siteId)) {
        this.siteId = data().deepCopy(fields()[5].schema(), other.siteId);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.driverId)) {
        this.driverId = data().deepCopy(fields()[6].schema(), other.driverId);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.name)) {
        this.name = data().deepCopy(fields()[7].schema(), other.name);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.imageUri)) {
        this.imageUri = data().deepCopy(fields()[8].schema(), other.imageUri);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.fmDriverId)) {
        this.fmDriverId = data().deepCopy(fields()[9].schema(), other.fmDriverId);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.employeeNumber)) {
        this.employeeNumber = data().deepCopy(fields()[10].schema(), other.employeeNumber);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.systemDriver)) {
        this.systemDriver = data().deepCopy(fields()[11].schema(), other.systemDriver);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.mobileNumber)) {
        this.mobileNumber = data().deepCopy(fields()[12].schema(), other.mobileNumber);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.email)) {
        this.email = data().deepCopy(fields()[13].schema(), other.email);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.extendedDriverId)) {
        this.extendedDriverId = data().deepCopy(fields()[14].schema(), other.extendedDriverId);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.extendedDriverIdType)) {
        this.extendedDriverIdType = data().deepCopy(fields()[15].schema(), other.extendedDriverIdType);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.country)) {
        this.country = data().deepCopy(fields()[16].schema(), other.country);
        fieldSetFlags()[16] = true;
      }
    }

    /**
      * Gets the value of the 'durableId' field.
      * @return The value.
      */
    public java.lang.CharSequence getDurableId() {
      return durableId;
    }

    /**
      * Sets the value of the 'durableId' field.
      * @param value The value of 'durableId'.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.dimension.AvroDriver.Builder setDurableId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.durableId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'durableId' field has been set.
      * @return True if the 'durableId' field has been set, false otherwise.
      */
    public boolean hasDurableId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'durableId' field.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.dimension.AvroDriver.Builder clearDurableId() {
      durableId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'ingestedDateUtc' field.
      * @return The value.
      */
    public org.joda.time.DateTime getIngestedDateUtc() {
      return ingestedDateUtc;
    }

    /**
      * Sets the value of the 'ingestedDateUtc' field.
      * @param value The value of 'ingestedDateUtc'.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.dimension.AvroDriver.Builder setIngestedDateUtc(org.joda.time.DateTime value) {
      validate(fields()[1], value);
      this.ingestedDateUtc = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'ingestedDateUtc' field has been set.
      * @return True if the 'ingestedDateUtc' field has been set, false otherwise.
      */
    public boolean hasIngestedDateUtc() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'ingestedDateUtc' field.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.dimension.AvroDriver.Builder clearIngestedDateUtc() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'subscriptionId' field.
      * @return The value.
      */
    public java.lang.Long getSubscriptionId() {
      return subscriptionId;
    }

    /**
      * Sets the value of the 'subscriptionId' field.
      * @param value The value of 'subscriptionId'.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.dimension.AvroDriver.Builder setSubscriptionId(java.lang.Long value) {
      validate(fields()[2], value);
      this.subscriptionId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'subscriptionId' field has been set.
      * @return True if the 'subscriptionId' field has been set, false otherwise.
      */
    public boolean hasSubscriptionId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'subscriptionId' field.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.dimension.AvroDriver.Builder clearSubscriptionId() {
      subscriptionId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'lineageCode' field.
      * @return The value.
      */
    public java.lang.Integer getLineageCode() {
      return lineageCode;
    }

    /**
      * Sets the value of the 'lineageCode' field.
      * @param value The value of 'lineageCode'.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.dimension.AvroDriver.Builder setLineageCode(java.lang.Integer value) {
      validate(fields()[3], value);
      this.lineageCode = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'lineageCode' field has been set.
      * @return True if the 'lineageCode' field has been set, false otherwise.
      */
    public boolean hasLineageCode() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'lineageCode' field.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.dimension.AvroDriver.Builder clearLineageCode() {
      lineageCode = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'schemaVersion' field.
      * Transport message support: avro schema version number
      * @return The value.
      */
    public java.lang.Integer getSchemaVersion() {
      return schemaVersion;
    }

    /**
      * Sets the value of the 'schemaVersion' field.
      * Transport message support: avro schema version number
      * @param value The value of 'schemaVersion'.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.dimension.AvroDriver.Builder setSchemaVersion(java.lang.Integer value) {
      validate(fields()[4], value);
      this.schemaVersion = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'schemaVersion' field has been set.
      * Transport message support: avro schema version number
      * @return True if the 'schemaVersion' field has been set, false otherwise.
      */
    public boolean hasSchemaVersion() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'schemaVersion' field.
      * Transport message support: avro schema version number
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.dimension.AvroDriver.Builder clearSchemaVersion() {
      schemaVersion = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'siteId' field.
      * @return The value.
      */
    public java.lang.Long getSiteId() {
      return siteId;
    }

    /**
      * Sets the value of the 'siteId' field.
      * @param value The value of 'siteId'.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.dimension.AvroDriver.Builder setSiteId(java.lang.Long value) {
      validate(fields()[5], value);
      this.siteId = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'siteId' field has been set.
      * @return True if the 'siteId' field has been set, false otherwise.
      */
    public boolean hasSiteId() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'siteId' field.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.dimension.AvroDriver.Builder clearSiteId() {
      siteId = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'driverId' field.
      * @return The value.
      */
    public java.lang.Long getDriverId() {
      return driverId;
    }

    /**
      * Sets the value of the 'driverId' field.
      * @param value The value of 'driverId'.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.dimension.AvroDriver.Builder setDriverId(java.lang.Long value) {
      validate(fields()[6], value);
      this.driverId = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'driverId' field has been set.
      * @return True if the 'driverId' field has been set, false otherwise.
      */
    public boolean hasDriverId() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'driverId' field.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.dimension.AvroDriver.Builder clearDriverId() {
      driverId = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }

    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.dimension.AvroDriver.Builder setName(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.name = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.dimension.AvroDriver.Builder clearName() {
      name = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'imageUri' field.
      * @return The value.
      */
    public java.lang.CharSequence getImageUri() {
      return imageUri;
    }

    /**
      * Sets the value of the 'imageUri' field.
      * @param value The value of 'imageUri'.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.dimension.AvroDriver.Builder setImageUri(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.imageUri = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'imageUri' field has been set.
      * @return True if the 'imageUri' field has been set, false otherwise.
      */
    public boolean hasImageUri() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'imageUri' field.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.dimension.AvroDriver.Builder clearImageUri() {
      imageUri = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'fmDriverId' field.
      * @return The value.
      */
    public java.lang.Long getFmDriverId() {
      return fmDriverId;
    }

    /**
      * Sets the value of the 'fmDriverId' field.
      * @param value The value of 'fmDriverId'.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.dimension.AvroDriver.Builder setFmDriverId(java.lang.Long value) {
      validate(fields()[9], value);
      this.fmDriverId = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'fmDriverId' field has been set.
      * @return True if the 'fmDriverId' field has been set, false otherwise.
      */
    public boolean hasFmDriverId() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'fmDriverId' field.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.dimension.AvroDriver.Builder clearFmDriverId() {
      fmDriverId = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'employeeNumber' field.
      * @return The value.
      */
    public java.lang.CharSequence getEmployeeNumber() {
      return employeeNumber;
    }

    /**
      * Sets the value of the 'employeeNumber' field.
      * @param value The value of 'employeeNumber'.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.dimension.AvroDriver.Builder setEmployeeNumber(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.employeeNumber = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'employeeNumber' field has been set.
      * @return True if the 'employeeNumber' field has been set, false otherwise.
      */
    public boolean hasEmployeeNumber() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'employeeNumber' field.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.dimension.AvroDriver.Builder clearEmployeeNumber() {
      employeeNumber = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'systemDriver' field.
      * @return The value.
      */
    public java.lang.Boolean getSystemDriver() {
      return systemDriver;
    }

    /**
      * Sets the value of the 'systemDriver' field.
      * @param value The value of 'systemDriver'.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.dimension.AvroDriver.Builder setSystemDriver(java.lang.Boolean value) {
      validate(fields()[11], value);
      this.systemDriver = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'systemDriver' field has been set.
      * @return True if the 'systemDriver' field has been set, false otherwise.
      */
    public boolean hasSystemDriver() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'systemDriver' field.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.dimension.AvroDriver.Builder clearSystemDriver() {
      systemDriver = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'mobileNumber' field.
      * @return The value.
      */
    public java.lang.CharSequence getMobileNumber() {
      return mobileNumber;
    }

    /**
      * Sets the value of the 'mobileNumber' field.
      * @param value The value of 'mobileNumber'.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.dimension.AvroDriver.Builder setMobileNumber(java.lang.CharSequence value) {
      validate(fields()[12], value);
      this.mobileNumber = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'mobileNumber' field has been set.
      * @return True if the 'mobileNumber' field has been set, false otherwise.
      */
    public boolean hasMobileNumber() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'mobileNumber' field.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.dimension.AvroDriver.Builder clearMobileNumber() {
      mobileNumber = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
      * Gets the value of the 'email' field.
      * @return The value.
      */
    public java.lang.CharSequence getEmail() {
      return email;
    }

    /**
      * Sets the value of the 'email' field.
      * @param value The value of 'email'.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.dimension.AvroDriver.Builder setEmail(java.lang.CharSequence value) {
      validate(fields()[13], value);
      this.email = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /**
      * Checks whether the 'email' field has been set.
      * @return True if the 'email' field has been set, false otherwise.
      */
    public boolean hasEmail() {
      return fieldSetFlags()[13];
    }


    /**
      * Clears the value of the 'email' field.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.dimension.AvroDriver.Builder clearEmail() {
      email = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    /**
      * Gets the value of the 'extendedDriverId' field.
      * @return The value.
      */
    public java.lang.CharSequence getExtendedDriverId() {
      return extendedDriverId;
    }

    /**
      * Sets the value of the 'extendedDriverId' field.
      * @param value The value of 'extendedDriverId'.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.dimension.AvroDriver.Builder setExtendedDriverId(java.lang.CharSequence value) {
      validate(fields()[14], value);
      this.extendedDriverId = value;
      fieldSetFlags()[14] = true;
      return this;
    }

    /**
      * Checks whether the 'extendedDriverId' field has been set.
      * @return True if the 'extendedDriverId' field has been set, false otherwise.
      */
    public boolean hasExtendedDriverId() {
      return fieldSetFlags()[14];
    }


    /**
      * Clears the value of the 'extendedDriverId' field.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.dimension.AvroDriver.Builder clearExtendedDriverId() {
      extendedDriverId = null;
      fieldSetFlags()[14] = false;
      return this;
    }

    /**
      * Gets the value of the 'extendedDriverIdType' field.
      * @return The value.
      */
    public java.lang.CharSequence getExtendedDriverIdType() {
      return extendedDriverIdType;
    }

    /**
      * Sets the value of the 'extendedDriverIdType' field.
      * @param value The value of 'extendedDriverIdType'.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.dimension.AvroDriver.Builder setExtendedDriverIdType(java.lang.CharSequence value) {
      validate(fields()[15], value);
      this.extendedDriverIdType = value;
      fieldSetFlags()[15] = true;
      return this;
    }

    /**
      * Checks whether the 'extendedDriverIdType' field has been set.
      * @return True if the 'extendedDriverIdType' field has been set, false otherwise.
      */
    public boolean hasExtendedDriverIdType() {
      return fieldSetFlags()[15];
    }


    /**
      * Clears the value of the 'extendedDriverIdType' field.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.dimension.AvroDriver.Builder clearExtendedDriverIdType() {
      extendedDriverIdType = null;
      fieldSetFlags()[15] = false;
      return this;
    }

    /**
      * Gets the value of the 'country' field.
      * @return The value.
      */
    public java.lang.CharSequence getCountry() {
      return country;
    }

    /**
      * Sets the value of the 'country' field.
      * @param value The value of 'country'.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.dimension.AvroDriver.Builder setCountry(java.lang.CharSequence value) {
      validate(fields()[16], value);
      this.country = value;
      fieldSetFlags()[16] = true;
      return this;
    }

    /**
      * Checks whether the 'country' field has been set.
      * @return True if the 'country' field has been set, false otherwise.
      */
    public boolean hasCountry() {
      return fieldSetFlags()[16];
    }


    /**
      * Clears the value of the 'country' field.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.dimension.AvroDriver.Builder clearCountry() {
      country = null;
      fieldSetFlags()[16] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AvroDriver build() {
      try {
        AvroDriver record = new AvroDriver();
        record.durableId = fieldSetFlags()[0] ? this.durableId : (java.lang.CharSequence) defaultValue(fields()[0], record.getConversion(0));
        record.ingestedDateUtc = fieldSetFlags()[1] ? this.ingestedDateUtc : (org.joda.time.DateTime) defaultValue(fields()[1], record.getConversion(1));
        record.subscriptionId = fieldSetFlags()[2] ? this.subscriptionId : (java.lang.Long) defaultValue(fields()[2], record.getConversion(2));
        record.lineageCode = fieldSetFlags()[3] ? this.lineageCode : (java.lang.Integer) defaultValue(fields()[3], record.getConversion(3));
        record.schemaVersion = fieldSetFlags()[4] ? this.schemaVersion : (java.lang.Integer) defaultValue(fields()[4], record.getConversion(4));
        record.siteId = fieldSetFlags()[5] ? this.siteId : (java.lang.Long) defaultValue(fields()[5], record.getConversion(5));
        record.driverId = fieldSetFlags()[6] ? this.driverId : (java.lang.Long) defaultValue(fields()[6], record.getConversion(6));
        record.name = fieldSetFlags()[7] ? this.name : (java.lang.CharSequence) defaultValue(fields()[7], record.getConversion(7));
        record.imageUri = fieldSetFlags()[8] ? this.imageUri : (java.lang.CharSequence) defaultValue(fields()[8], record.getConversion(8));
        record.fmDriverId = fieldSetFlags()[9] ? this.fmDriverId : (java.lang.Long) defaultValue(fields()[9], record.getConversion(9));
        record.employeeNumber = fieldSetFlags()[10] ? this.employeeNumber : (java.lang.CharSequence) defaultValue(fields()[10], record.getConversion(10));
        record.systemDriver = fieldSetFlags()[11] ? this.systemDriver : (java.lang.Boolean) defaultValue(fields()[11], record.getConversion(11));
        record.mobileNumber = fieldSetFlags()[12] ? this.mobileNumber : (java.lang.CharSequence) defaultValue(fields()[12], record.getConversion(12));
        record.email = fieldSetFlags()[13] ? this.email : (java.lang.CharSequence) defaultValue(fields()[13], record.getConversion(13));
        record.extendedDriverId = fieldSetFlags()[14] ? this.extendedDriverId : (java.lang.CharSequence) defaultValue(fields()[14], record.getConversion(14));
        record.extendedDriverIdType = fieldSetFlags()[15] ? this.extendedDriverIdType : (java.lang.CharSequence) defaultValue(fields()[15], record.getConversion(15));
        record.country = fieldSetFlags()[16] ? this.country : (java.lang.CharSequence) defaultValue(fields()[16], record.getConversion(16));
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AvroDriver>
    WRITER$ = (org.apache.avro.io.DatumWriter<AvroDriver>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AvroDriver>
    READER$ = (org.apache.avro.io.DatumReader<AvroDriver>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
