/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.epam.tcodata.models.avro.dimension;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class AvroLocation extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5655500179616411363L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AvroLocation\",\"namespace\":\"com.epam.tcodata.models.avro.dimension\",\"fields\":[{\"name\":\"durableId\",\"type\":[\"null\",\"string\"]},{\"name\":\"ingestedDateUtc\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}},{\"name\":\"subscriptionId\",\"type\":[\"null\",\"long\"]},{\"name\":\"lineageCode\",\"type\":[\"null\",\"int\"]},{\"name\":\"schemaVersion\",\"type\":[\"null\",\"int\"],\"doc\":\"Transport message support: avro schema version number\"},{\"name\":\"locationId\",\"type\":[\"null\",\"long\"]},{\"name\":\"organisationId\",\"type\":[\"null\",\"long\"]},{\"name\":\"groupId\",\"type\":[\"null\",\"long\"]},{\"name\":\"name\",\"type\":[\"null\",\"string\"]},{\"name\":\"address\",\"type\":[\"null\",\"string\"]},{\"name\":\"locationType\",\"type\":[\"null\",\"string\"]},{\"name\":\"shapeType\",\"type\":[\"null\",\"string\"]},{\"name\":\"radius\",\"type\":[\"null\",\"double\"]},{\"name\":\"shapeWkt\",\"type\":[\"null\",\"string\"]},{\"name\":\"deleted\",\"type\":[\"null\",\"boolean\"]},{\"name\":\"colourOnMap\",\"type\":[\"null\",\"string\"]},{\"name\":\"opacityOnMap\",\"type\":[\"null\",\"double\"]},{\"name\":\"temporary\",\"type\":[\"null\",\"boolean\"]},{\"name\":\"externalReference\",\"type\":[\"null\",\"string\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AvroLocation> ENCODER =
      new BinaryMessageEncoder<AvroLocation>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AvroLocation> DECODER =
      new BinaryMessageDecoder<AvroLocation>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<AvroLocation> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<AvroLocation> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<AvroLocation>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this AvroLocation to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a AvroLocation from a ByteBuffer. */
  public static AvroLocation fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence durableId;
  @Deprecated public org.joda.time.DateTime ingestedDateUtc;
  @Deprecated public java.lang.Long subscriptionId;
  @Deprecated public java.lang.Integer lineageCode;
  /** Transport message support: avro schema version number */
  @Deprecated public java.lang.Integer schemaVersion;
  @Deprecated public java.lang.Long locationId;
  @Deprecated public java.lang.Long organisationId;
  @Deprecated public java.lang.Long groupId;
  @Deprecated public java.lang.CharSequence name;
  @Deprecated public java.lang.CharSequence address;
  @Deprecated public java.lang.CharSequence locationType;
  @Deprecated public java.lang.CharSequence shapeType;
  @Deprecated public java.lang.Double radius;
  @Deprecated public java.lang.CharSequence shapeWkt;
  @Deprecated public java.lang.Boolean deleted;
  @Deprecated public java.lang.CharSequence colourOnMap;
  @Deprecated public java.lang.Double opacityOnMap;
  @Deprecated public java.lang.Boolean temporary;
  @Deprecated public java.lang.CharSequence externalReference;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AvroLocation() {}

  /**
   * All-args constructor.
   * @param durableId The new value for durableId
   * @param ingestedDateUtc The new value for ingestedDateUtc
   * @param subscriptionId The new value for subscriptionId
   * @param lineageCode The new value for lineageCode
   * @param schemaVersion Transport message support: avro schema version number
   * @param locationId The new value for locationId
   * @param organisationId The new value for organisationId
   * @param groupId The new value for groupId
   * @param name The new value for name
   * @param address The new value for address
   * @param locationType The new value for locationType
   * @param shapeType The new value for shapeType
   * @param radius The new value for radius
   * @param shapeWkt The new value for shapeWkt
   * @param deleted The new value for deleted
   * @param colourOnMap The new value for colourOnMap
   * @param opacityOnMap The new value for opacityOnMap
   * @param temporary The new value for temporary
   * @param externalReference The new value for externalReference
   */
  public AvroLocation(java.lang.CharSequence durableId, org.joda.time.DateTime ingestedDateUtc, java.lang.Long subscriptionId, java.lang.Integer lineageCode, java.lang.Integer schemaVersion, java.lang.Long locationId, java.lang.Long organisationId, java.lang.Long groupId, java.lang.CharSequence name, java.lang.CharSequence address, java.lang.CharSequence locationType, java.lang.CharSequence shapeType, java.lang.Double radius, java.lang.CharSequence shapeWkt, java.lang.Boolean deleted, java.lang.CharSequence colourOnMap, java.lang.Double opacityOnMap, java.lang.Boolean temporary, java.lang.CharSequence externalReference) {
    this.durableId = durableId;
    this.ingestedDateUtc = ingestedDateUtc;
    this.subscriptionId = subscriptionId;
    this.lineageCode = lineageCode;
    this.schemaVersion = schemaVersion;
    this.locationId = locationId;
    this.organisationId = organisationId;
    this.groupId = groupId;
    this.name = name;
    this.address = address;
    this.locationType = locationType;
    this.shapeType = shapeType;
    this.radius = radius;
    this.shapeWkt = shapeWkt;
    this.deleted = deleted;
    this.colourOnMap = colourOnMap;
    this.opacityOnMap = opacityOnMap;
    this.temporary = temporary;
    this.externalReference = externalReference;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return durableId;
    case 1: return ingestedDateUtc;
    case 2: return subscriptionId;
    case 3: return lineageCode;
    case 4: return schemaVersion;
    case 5: return locationId;
    case 6: return organisationId;
    case 7: return groupId;
    case 8: return name;
    case 9: return address;
    case 10: return locationType;
    case 11: return shapeType;
    case 12: return radius;
    case 13: return shapeWkt;
    case 14: return deleted;
    case 15: return colourOnMap;
    case 16: return opacityOnMap;
    case 17: return temporary;
    case 18: return externalReference;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  protected static final org.apache.avro.data.TimeConversions.DateConversion DATE_CONVERSION = new org.apache.avro.data.TimeConversions.DateConversion();
  protected static final org.apache.avro.data.TimeConversions.TimeConversion TIME_CONVERSION = new org.apache.avro.data.TimeConversions.TimeConversion();
  protected static final org.apache.avro.data.TimeConversions.TimestampConversion TIMESTAMP_CONVERSION = new org.apache.avro.data.TimeConversions.TimestampConversion();
  protected static final org.apache.avro.Conversions.DecimalConversion DECIMAL_CONVERSION = new org.apache.avro.Conversions.DecimalConversion();

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      TIMESTAMP_CONVERSION,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: durableId = (java.lang.CharSequence)value$; break;
    case 1: ingestedDateUtc = (org.joda.time.DateTime)value$; break;
    case 2: subscriptionId = (java.lang.Long)value$; break;
    case 3: lineageCode = (java.lang.Integer)value$; break;
    case 4: schemaVersion = (java.lang.Integer)value$; break;
    case 5: locationId = (java.lang.Long)value$; break;
    case 6: organisationId = (java.lang.Long)value$; break;
    case 7: groupId = (java.lang.Long)value$; break;
    case 8: name = (java.lang.CharSequence)value$; break;
    case 9: address = (java.lang.CharSequence)value$; break;
    case 10: locationType = (java.lang.CharSequence)value$; break;
    case 11: shapeType = (java.lang.CharSequence)value$; break;
    case 12: radius = (java.lang.Double)value$; break;
    case 13: shapeWkt = (java.lang.CharSequence)value$; break;
    case 14: deleted = (java.lang.Boolean)value$; break;
    case 15: colourOnMap = (java.lang.CharSequence)value$; break;
    case 16: opacityOnMap = (java.lang.Double)value$; break;
    case 17: temporary = (java.lang.Boolean)value$; break;
    case 18: externalReference = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'durableId' field.
   * @return The value of the 'durableId' field.
   */
  public java.lang.CharSequence getDurableId() {
    return durableId;
  }

  /**
   * Sets the value of the 'durableId' field.
   * @param value the value to set.
   */
  public void setDurableId(java.lang.CharSequence value) {
    this.durableId = value;
  }

  /**
   * Gets the value of the 'ingestedDateUtc' field.
   * @return The value of the 'ingestedDateUtc' field.
   */
  public org.joda.time.DateTime getIngestedDateUtc() {
    return ingestedDateUtc;
  }

  /**
   * Sets the value of the 'ingestedDateUtc' field.
   * @param value the value to set.
   */
  public void setIngestedDateUtc(org.joda.time.DateTime value) {
    this.ingestedDateUtc = value;
  }

  /**
   * Gets the value of the 'subscriptionId' field.
   * @return The value of the 'subscriptionId' field.
   */
  public java.lang.Long getSubscriptionId() {
    return subscriptionId;
  }

  /**
   * Sets the value of the 'subscriptionId' field.
   * @param value the value to set.
   */
  public void setSubscriptionId(java.lang.Long value) {
    this.subscriptionId = value;
  }

  /**
   * Gets the value of the 'lineageCode' field.
   * @return The value of the 'lineageCode' field.
   */
  public java.lang.Integer getLineageCode() {
    return lineageCode;
  }

  /**
   * Sets the value of the 'lineageCode' field.
   * @param value the value to set.
   */
  public void setLineageCode(java.lang.Integer value) {
    this.lineageCode = value;
  }

  /**
   * Gets the value of the 'schemaVersion' field.
   * @return Transport message support: avro schema version number
   */
  public java.lang.Integer getSchemaVersion() {
    return schemaVersion;
  }

  /**
   * Sets the value of the 'schemaVersion' field.
   * Transport message support: avro schema version number
   * @param value the value to set.
   */
  public void setSchemaVersion(java.lang.Integer value) {
    this.schemaVersion = value;
  }

  /**
   * Gets the value of the 'locationId' field.
   * @return The value of the 'locationId' field.
   */
  public java.lang.Long getLocationId() {
    return locationId;
  }

  /**
   * Sets the value of the 'locationId' field.
   * @param value the value to set.
   */
  public void setLocationId(java.lang.Long value) {
    this.locationId = value;
  }

  /**
   * Gets the value of the 'organisationId' field.
   * @return The value of the 'organisationId' field.
   */
  public java.lang.Long getOrganisationId() {
    return organisationId;
  }

  /**
   * Sets the value of the 'organisationId' field.
   * @param value the value to set.
   */
  public void setOrganisationId(java.lang.Long value) {
    this.organisationId = value;
  }

  /**
   * Gets the value of the 'groupId' field.
   * @return The value of the 'groupId' field.
   */
  public java.lang.Long getGroupId() {
    return groupId;
  }

  /**
   * Sets the value of the 'groupId' field.
   * @param value the value to set.
   */
  public void setGroupId(java.lang.Long value) {
    this.groupId = value;
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'address' field.
   * @return The value of the 'address' field.
   */
  public java.lang.CharSequence getAddress() {
    return address;
  }

  /**
   * Sets the value of the 'address' field.
   * @param value the value to set.
   */
  public void setAddress(java.lang.CharSequence value) {
    this.address = value;
  }

  /**
   * Gets the value of the 'locationType' field.
   * @return The value of the 'locationType' field.
   */
  public java.lang.CharSequence getLocationType() {
    return locationType;
  }

  /**
   * Sets the value of the 'locationType' field.
   * @param value the value to set.
   */
  public void setLocationType(java.lang.CharSequence value) {
    this.locationType = value;
  }

  /**
   * Gets the value of the 'shapeType' field.
   * @return The value of the 'shapeType' field.
   */
  public java.lang.CharSequence getShapeType() {
    return shapeType;
  }

  /**
   * Sets the value of the 'shapeType' field.
   * @param value the value to set.
   */
  public void setShapeType(java.lang.CharSequence value) {
    this.shapeType = value;
  }

  /**
   * Gets the value of the 'radius' field.
   * @return The value of the 'radius' field.
   */
  public java.lang.Double getRadius() {
    return radius;
  }

  /**
   * Sets the value of the 'radius' field.
   * @param value the value to set.
   */
  public void setRadius(java.lang.Double value) {
    this.radius = value;
  }

  /**
   * Gets the value of the 'shapeWkt' field.
   * @return The value of the 'shapeWkt' field.
   */
  public java.lang.CharSequence getShapeWkt() {
    return shapeWkt;
  }

  /**
   * Sets the value of the 'shapeWkt' field.
   * @param value the value to set.
   */
  public void setShapeWkt(java.lang.CharSequence value) {
    this.shapeWkt = value;
  }

  /**
   * Gets the value of the 'deleted' field.
   * @return The value of the 'deleted' field.
   */
  public java.lang.Boolean getDeleted() {
    return deleted;
  }

  /**
   * Sets the value of the 'deleted' field.
   * @param value the value to set.
   */
  public void setDeleted(java.lang.Boolean value) {
    this.deleted = value;
  }

  /**
   * Gets the value of the 'colourOnMap' field.
   * @return The value of the 'colourOnMap' field.
   */
  public java.lang.CharSequence getColourOnMap() {
    return colourOnMap;
  }

  /**
   * Sets the value of the 'colourOnMap' field.
   * @param value the value to set.
   */
  public void setColourOnMap(java.lang.CharSequence value) {
    this.colourOnMap = value;
  }

  /**
   * Gets the value of the 'opacityOnMap' field.
   * @return The value of the 'opacityOnMap' field.
   */
  public java.lang.Double getOpacityOnMap() {
    return opacityOnMap;
  }

  /**
   * Sets the value of the 'opacityOnMap' field.
   * @param value the value to set.
   */
  public void setOpacityOnMap(java.lang.Double value) {
    this.opacityOnMap = value;
  }

  /**
   * Gets the value of the 'temporary' field.
   * @return The value of the 'temporary' field.
   */
  public java.lang.Boolean getTemporary() {
    return temporary;
  }

  /**
   * Sets the value of the 'temporary' field.
   * @param value the value to set.
   */
  public void setTemporary(java.lang.Boolean value) {
    this.temporary = value;
  }

  /**
   * Gets the value of the 'externalReference' field.
   * @return The value of the 'externalReference' field.
   */
  public java.lang.CharSequence getExternalReference() {
    return externalReference;
  }

  /**
   * Sets the value of the 'externalReference' field.
   * @param value the value to set.
   */
  public void setExternalReference(java.lang.CharSequence value) {
    this.externalReference = value;
  }

  /**
   * Creates a new AvroLocation RecordBuilder.
   * @return A new AvroLocation RecordBuilder
   */
  public static com.epam.tcodata.models.avro.dimension.AvroLocation.Builder newBuilder() {
    return new com.epam.tcodata.models.avro.dimension.AvroLocation.Builder();
  }

  /**
   * Creates a new AvroLocation RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AvroLocation RecordBuilder
   */
  public static com.epam.tcodata.models.avro.dimension.AvroLocation.Builder newBuilder(com.epam.tcodata.models.avro.dimension.AvroLocation.Builder other) {
    return new com.epam.tcodata.models.avro.dimension.AvroLocation.Builder(other);
  }

  /**
   * Creates a new AvroLocation RecordBuilder by copying an existing AvroLocation instance.
   * @param other The existing instance to copy.
   * @return A new AvroLocation RecordBuilder
   */
  public static com.epam.tcodata.models.avro.dimension.AvroLocation.Builder newBuilder(com.epam.tcodata.models.avro.dimension.AvroLocation other) {
    return new com.epam.tcodata.models.avro.dimension.AvroLocation.Builder(other);
  }

  /**
   * RecordBuilder for AvroLocation instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AvroLocation>
    implements org.apache.avro.data.RecordBuilder<AvroLocation> {

    private java.lang.CharSequence durableId;
    private org.joda.time.DateTime ingestedDateUtc;
    private java.lang.Long subscriptionId;
    private java.lang.Integer lineageCode;
    /** Transport message support: avro schema version number */
    private java.lang.Integer schemaVersion;
    private java.lang.Long locationId;
    private java.lang.Long organisationId;
    private java.lang.Long groupId;
    private java.lang.CharSequence name;
    private java.lang.CharSequence address;
    private java.lang.CharSequence locationType;
    private java.lang.CharSequence shapeType;
    private java.lang.Double radius;
    private java.lang.CharSequence shapeWkt;
    private java.lang.Boolean deleted;
    private java.lang.CharSequence colourOnMap;
    private java.lang.Double opacityOnMap;
    private java.lang.Boolean temporary;
    private java.lang.CharSequence externalReference;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.epam.tcodata.models.avro.dimension.AvroLocation.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.durableId)) {
        this.durableId = data().deepCopy(fields()[0].schema(), other.durableId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.ingestedDateUtc)) {
        this.ingestedDateUtc = data().deepCopy(fields()[1].schema(), other.ingestedDateUtc);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.subscriptionId)) {
        this.subscriptionId = data().deepCopy(fields()[2].schema(), other.subscriptionId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.lineageCode)) {
        this.lineageCode = data().deepCopy(fields()[3].schema(), other.lineageCode);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.schemaVersion)) {
        this.schemaVersion = data().deepCopy(fields()[4].schema(), other.schemaVersion);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.locationId)) {
        this.locationId = data().deepCopy(fields()[5].schema(), other.locationId);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.organisationId)) {
        this.organisationId = data().deepCopy(fields()[6].schema(), other.organisationId);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.groupId)) {
        this.groupId = data().deepCopy(fields()[7].schema(), other.groupId);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.name)) {
        this.name = data().deepCopy(fields()[8].schema(), other.name);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.address)) {
        this.address = data().deepCopy(fields()[9].schema(), other.address);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.locationType)) {
        this.locationType = data().deepCopy(fields()[10].schema(), other.locationType);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.shapeType)) {
        this.shapeType = data().deepCopy(fields()[11].schema(), other.shapeType);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.radius)) {
        this.radius = data().deepCopy(fields()[12].schema(), other.radius);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.shapeWkt)) {
        this.shapeWkt = data().deepCopy(fields()[13].schema(), other.shapeWkt);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.deleted)) {
        this.deleted = data().deepCopy(fields()[14].schema(), other.deleted);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.colourOnMap)) {
        this.colourOnMap = data().deepCopy(fields()[15].schema(), other.colourOnMap);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.opacityOnMap)) {
        this.opacityOnMap = data().deepCopy(fields()[16].schema(), other.opacityOnMap);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.temporary)) {
        this.temporary = data().deepCopy(fields()[17].schema(), other.temporary);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.externalReference)) {
        this.externalReference = data().deepCopy(fields()[18].schema(), other.externalReference);
        fieldSetFlags()[18] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing AvroLocation instance
     * @param other The existing instance to copy.
     */
    private Builder(com.epam.tcodata.models.avro.dimension.AvroLocation other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.durableId)) {
        this.durableId = data().deepCopy(fields()[0].schema(), other.durableId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.ingestedDateUtc)) {
        this.ingestedDateUtc = data().deepCopy(fields()[1].schema(), other.ingestedDateUtc);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.subscriptionId)) {
        this.subscriptionId = data().deepCopy(fields()[2].schema(), other.subscriptionId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.lineageCode)) {
        this.lineageCode = data().deepCopy(fields()[3].schema(), other.lineageCode);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.schemaVersion)) {
        this.schemaVersion = data().deepCopy(fields()[4].schema(), other.schemaVersion);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.locationId)) {
        this.locationId = data().deepCopy(fields()[5].schema(), other.locationId);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.organisationId)) {
        this.organisationId = data().deepCopy(fields()[6].schema(), other.organisationId);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.groupId)) {
        this.groupId = data().deepCopy(fields()[7].schema(), other.groupId);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.name)) {
        this.name = data().deepCopy(fields()[8].schema(), other.name);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.address)) {
        this.address = data().deepCopy(fields()[9].schema(), other.address);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.locationType)) {
        this.locationType = data().deepCopy(fields()[10].schema(), other.locationType);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.shapeType)) {
        this.shapeType = data().deepCopy(fields()[11].schema(), other.shapeType);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.radius)) {
        this.radius = data().deepCopy(fields()[12].schema(), other.radius);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.shapeWkt)) {
        this.shapeWkt = data().deepCopy(fields()[13].schema(), other.shapeWkt);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.deleted)) {
        this.deleted = data().deepCopy(fields()[14].schema(), other.deleted);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.colourOnMap)) {
        this.colourOnMap = data().deepCopy(fields()[15].schema(), other.colourOnMap);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.opacityOnMap)) {
        this.opacityOnMap = data().deepCopy(fields()[16].schema(), other.opacityOnMap);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.temporary)) {
        this.temporary = data().deepCopy(fields()[17].schema(), other.temporary);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.externalReference)) {
        this.externalReference = data().deepCopy(fields()[18].schema(), other.externalReference);
        fieldSetFlags()[18] = true;
      }
    }

    /**
      * Gets the value of the 'durableId' field.
      * @return The value.
      */
    public java.lang.CharSequence getDurableId() {
      return durableId;
    }

    /**
      * Sets the value of the 'durableId' field.
      * @param value The value of 'durableId'.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.dimension.AvroLocation.Builder setDurableId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.durableId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'durableId' field has been set.
      * @return True if the 'durableId' field has been set, false otherwise.
      */
    public boolean hasDurableId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'durableId' field.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.dimension.AvroLocation.Builder clearDurableId() {
      durableId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'ingestedDateUtc' field.
      * @return The value.
      */
    public org.joda.time.DateTime getIngestedDateUtc() {
      return ingestedDateUtc;
    }

    /**
      * Sets the value of the 'ingestedDateUtc' field.
      * @param value The value of 'ingestedDateUtc'.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.dimension.AvroLocation.Builder setIngestedDateUtc(org.joda.time.DateTime value) {
      validate(fields()[1], value);
      this.ingestedDateUtc = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'ingestedDateUtc' field has been set.
      * @return True if the 'ingestedDateUtc' field has been set, false otherwise.
      */
    public boolean hasIngestedDateUtc() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'ingestedDateUtc' field.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.dimension.AvroLocation.Builder clearIngestedDateUtc() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'subscriptionId' field.
      * @return The value.
      */
    public java.lang.Long getSubscriptionId() {
      return subscriptionId;
    }

    /**
      * Sets the value of the 'subscriptionId' field.
      * @param value The value of 'subscriptionId'.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.dimension.AvroLocation.Builder setSubscriptionId(java.lang.Long value) {
      validate(fields()[2], value);
      this.subscriptionId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'subscriptionId' field has been set.
      * @return True if the 'subscriptionId' field has been set, false otherwise.
      */
    public boolean hasSubscriptionId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'subscriptionId' field.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.dimension.AvroLocation.Builder clearSubscriptionId() {
      subscriptionId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'lineageCode' field.
      * @return The value.
      */
    public java.lang.Integer getLineageCode() {
      return lineageCode;
    }

    /**
      * Sets the value of the 'lineageCode' field.
      * @param value The value of 'lineageCode'.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.dimension.AvroLocation.Builder setLineageCode(java.lang.Integer value) {
      validate(fields()[3], value);
      this.lineageCode = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'lineageCode' field has been set.
      * @return True if the 'lineageCode' field has been set, false otherwise.
      */
    public boolean hasLineageCode() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'lineageCode' field.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.dimension.AvroLocation.Builder clearLineageCode() {
      lineageCode = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'schemaVersion' field.
      * Transport message support: avro schema version number
      * @return The value.
      */
    public java.lang.Integer getSchemaVersion() {
      return schemaVersion;
    }

    /**
      * Sets the value of the 'schemaVersion' field.
      * Transport message support: avro schema version number
      * @param value The value of 'schemaVersion'.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.dimension.AvroLocation.Builder setSchemaVersion(java.lang.Integer value) {
      validate(fields()[4], value);
      this.schemaVersion = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'schemaVersion' field has been set.
      * Transport message support: avro schema version number
      * @return True if the 'schemaVersion' field has been set, false otherwise.
      */
    public boolean hasSchemaVersion() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'schemaVersion' field.
      * Transport message support: avro schema version number
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.dimension.AvroLocation.Builder clearSchemaVersion() {
      schemaVersion = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'locationId' field.
      * @return The value.
      */
    public java.lang.Long getLocationId() {
      return locationId;
    }

    /**
      * Sets the value of the 'locationId' field.
      * @param value The value of 'locationId'.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.dimension.AvroLocation.Builder setLocationId(java.lang.Long value) {
      validate(fields()[5], value);
      this.locationId = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'locationId' field has been set.
      * @return True if the 'locationId' field has been set, false otherwise.
      */
    public boolean hasLocationId() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'locationId' field.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.dimension.AvroLocation.Builder clearLocationId() {
      locationId = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'organisationId' field.
      * @return The value.
      */
    public java.lang.Long getOrganisationId() {
      return organisationId;
    }

    /**
      * Sets the value of the 'organisationId' field.
      * @param value The value of 'organisationId'.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.dimension.AvroLocation.Builder setOrganisationId(java.lang.Long value) {
      validate(fields()[6], value);
      this.organisationId = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'organisationId' field has been set.
      * @return True if the 'organisationId' field has been set, false otherwise.
      */
    public boolean hasOrganisationId() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'organisationId' field.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.dimension.AvroLocation.Builder clearOrganisationId() {
      organisationId = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'groupId' field.
      * @return The value.
      */
    public java.lang.Long getGroupId() {
      return groupId;
    }

    /**
      * Sets the value of the 'groupId' field.
      * @param value The value of 'groupId'.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.dimension.AvroLocation.Builder setGroupId(java.lang.Long value) {
      validate(fields()[7], value);
      this.groupId = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'groupId' field has been set.
      * @return True if the 'groupId' field has been set, false otherwise.
      */
    public boolean hasGroupId() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'groupId' field.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.dimension.AvroLocation.Builder clearGroupId() {
      groupId = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }

    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.dimension.AvroLocation.Builder setName(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.name = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.dimension.AvroLocation.Builder clearName() {
      name = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'address' field.
      * @return The value.
      */
    public java.lang.CharSequence getAddress() {
      return address;
    }

    /**
      * Sets the value of the 'address' field.
      * @param value The value of 'address'.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.dimension.AvroLocation.Builder setAddress(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.address = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'address' field has been set.
      * @return True if the 'address' field has been set, false otherwise.
      */
    public boolean hasAddress() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'address' field.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.dimension.AvroLocation.Builder clearAddress() {
      address = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'locationType' field.
      * @return The value.
      */
    public java.lang.CharSequence getLocationType() {
      return locationType;
    }

    /**
      * Sets the value of the 'locationType' field.
      * @param value The value of 'locationType'.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.dimension.AvroLocation.Builder setLocationType(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.locationType = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'locationType' field has been set.
      * @return True if the 'locationType' field has been set, false otherwise.
      */
    public boolean hasLocationType() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'locationType' field.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.dimension.AvroLocation.Builder clearLocationType() {
      locationType = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'shapeType' field.
      * @return The value.
      */
    public java.lang.CharSequence getShapeType() {
      return shapeType;
    }

    /**
      * Sets the value of the 'shapeType' field.
      * @param value The value of 'shapeType'.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.dimension.AvroLocation.Builder setShapeType(java.lang.CharSequence value) {
      validate(fields()[11], value);
      this.shapeType = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'shapeType' field has been set.
      * @return True if the 'shapeType' field has been set, false otherwise.
      */
    public boolean hasShapeType() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'shapeType' field.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.dimension.AvroLocation.Builder clearShapeType() {
      shapeType = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'radius' field.
      * @return The value.
      */
    public java.lang.Double getRadius() {
      return radius;
    }

    /**
      * Sets the value of the 'radius' field.
      * @param value The value of 'radius'.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.dimension.AvroLocation.Builder setRadius(java.lang.Double value) {
      validate(fields()[12], value);
      this.radius = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'radius' field has been set.
      * @return True if the 'radius' field has been set, false otherwise.
      */
    public boolean hasRadius() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'radius' field.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.dimension.AvroLocation.Builder clearRadius() {
      radius = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
      * Gets the value of the 'shapeWkt' field.
      * @return The value.
      */
    public java.lang.CharSequence getShapeWkt() {
      return shapeWkt;
    }

    /**
      * Sets the value of the 'shapeWkt' field.
      * @param value The value of 'shapeWkt'.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.dimension.AvroLocation.Builder setShapeWkt(java.lang.CharSequence value) {
      validate(fields()[13], value);
      this.shapeWkt = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /**
      * Checks whether the 'shapeWkt' field has been set.
      * @return True if the 'shapeWkt' field has been set, false otherwise.
      */
    public boolean hasShapeWkt() {
      return fieldSetFlags()[13];
    }


    /**
      * Clears the value of the 'shapeWkt' field.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.dimension.AvroLocation.Builder clearShapeWkt() {
      shapeWkt = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    /**
      * Gets the value of the 'deleted' field.
      * @return The value.
      */
    public java.lang.Boolean getDeleted() {
      return deleted;
    }

    /**
      * Sets the value of the 'deleted' field.
      * @param value The value of 'deleted'.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.dimension.AvroLocation.Builder setDeleted(java.lang.Boolean value) {
      validate(fields()[14], value);
      this.deleted = value;
      fieldSetFlags()[14] = true;
      return this;
    }

    /**
      * Checks whether the 'deleted' field has been set.
      * @return True if the 'deleted' field has been set, false otherwise.
      */
    public boolean hasDeleted() {
      return fieldSetFlags()[14];
    }


    /**
      * Clears the value of the 'deleted' field.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.dimension.AvroLocation.Builder clearDeleted() {
      deleted = null;
      fieldSetFlags()[14] = false;
      return this;
    }

    /**
      * Gets the value of the 'colourOnMap' field.
      * @return The value.
      */
    public java.lang.CharSequence getColourOnMap() {
      return colourOnMap;
    }

    /**
      * Sets the value of the 'colourOnMap' field.
      * @param value The value of 'colourOnMap'.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.dimension.AvroLocation.Builder setColourOnMap(java.lang.CharSequence value) {
      validate(fields()[15], value);
      this.colourOnMap = value;
      fieldSetFlags()[15] = true;
      return this;
    }

    /**
      * Checks whether the 'colourOnMap' field has been set.
      * @return True if the 'colourOnMap' field has been set, false otherwise.
      */
    public boolean hasColourOnMap() {
      return fieldSetFlags()[15];
    }


    /**
      * Clears the value of the 'colourOnMap' field.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.dimension.AvroLocation.Builder clearColourOnMap() {
      colourOnMap = null;
      fieldSetFlags()[15] = false;
      return this;
    }

    /**
      * Gets the value of the 'opacityOnMap' field.
      * @return The value.
      */
    public java.lang.Double getOpacityOnMap() {
      return opacityOnMap;
    }

    /**
      * Sets the value of the 'opacityOnMap' field.
      * @param value The value of 'opacityOnMap'.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.dimension.AvroLocation.Builder setOpacityOnMap(java.lang.Double value) {
      validate(fields()[16], value);
      this.opacityOnMap = value;
      fieldSetFlags()[16] = true;
      return this;
    }

    /**
      * Checks whether the 'opacityOnMap' field has been set.
      * @return True if the 'opacityOnMap' field has been set, false otherwise.
      */
    public boolean hasOpacityOnMap() {
      return fieldSetFlags()[16];
    }


    /**
      * Clears the value of the 'opacityOnMap' field.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.dimension.AvroLocation.Builder clearOpacityOnMap() {
      opacityOnMap = null;
      fieldSetFlags()[16] = false;
      return this;
    }

    /**
      * Gets the value of the 'temporary' field.
      * @return The value.
      */
    public java.lang.Boolean getTemporary() {
      return temporary;
    }

    /**
      * Sets the value of the 'temporary' field.
      * @param value The value of 'temporary'.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.dimension.AvroLocation.Builder setTemporary(java.lang.Boolean value) {
      validate(fields()[17], value);
      this.temporary = value;
      fieldSetFlags()[17] = true;
      return this;
    }

    /**
      * Checks whether the 'temporary' field has been set.
      * @return True if the 'temporary' field has been set, false otherwise.
      */
    public boolean hasTemporary() {
      return fieldSetFlags()[17];
    }


    /**
      * Clears the value of the 'temporary' field.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.dimension.AvroLocation.Builder clearTemporary() {
      temporary = null;
      fieldSetFlags()[17] = false;
      return this;
    }

    /**
      * Gets the value of the 'externalReference' field.
      * @return The value.
      */
    public java.lang.CharSequence getExternalReference() {
      return externalReference;
    }

    /**
      * Sets the value of the 'externalReference' field.
      * @param value The value of 'externalReference'.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.dimension.AvroLocation.Builder setExternalReference(java.lang.CharSequence value) {
      validate(fields()[18], value);
      this.externalReference = value;
      fieldSetFlags()[18] = true;
      return this;
    }

    /**
      * Checks whether the 'externalReference' field has been set.
      * @return True if the 'externalReference' field has been set, false otherwise.
      */
    public boolean hasExternalReference() {
      return fieldSetFlags()[18];
    }


    /**
      * Clears the value of the 'externalReference' field.
      * @return This builder.
      */
    public com.epam.tcodata.models.avro.dimension.AvroLocation.Builder clearExternalReference() {
      externalReference = null;
      fieldSetFlags()[18] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AvroLocation build() {
      try {
        AvroLocation record = new AvroLocation();
        record.durableId = fieldSetFlags()[0] ? this.durableId : (java.lang.CharSequence) defaultValue(fields()[0], record.getConversion(0));
        record.ingestedDateUtc = fieldSetFlags()[1] ? this.ingestedDateUtc : (org.joda.time.DateTime) defaultValue(fields()[1], record.getConversion(1));
        record.subscriptionId = fieldSetFlags()[2] ? this.subscriptionId : (java.lang.Long) defaultValue(fields()[2], record.getConversion(2));
        record.lineageCode = fieldSetFlags()[3] ? this.lineageCode : (java.lang.Integer) defaultValue(fields()[3], record.getConversion(3));
        record.schemaVersion = fieldSetFlags()[4] ? this.schemaVersion : (java.lang.Integer) defaultValue(fields()[4], record.getConversion(4));
        record.locationId = fieldSetFlags()[5] ? this.locationId : (java.lang.Long) defaultValue(fields()[5], record.getConversion(5));
        record.organisationId = fieldSetFlags()[6] ? this.organisationId : (java.lang.Long) defaultValue(fields()[6], record.getConversion(6));
        record.groupId = fieldSetFlags()[7] ? this.groupId : (java.lang.Long) defaultValue(fields()[7], record.getConversion(7));
        record.name = fieldSetFlags()[8] ? this.name : (java.lang.CharSequence) defaultValue(fields()[8], record.getConversion(8));
        record.address = fieldSetFlags()[9] ? this.address : (java.lang.CharSequence) defaultValue(fields()[9], record.getConversion(9));
        record.locationType = fieldSetFlags()[10] ? this.locationType : (java.lang.CharSequence) defaultValue(fields()[10], record.getConversion(10));
        record.shapeType = fieldSetFlags()[11] ? this.shapeType : (java.lang.CharSequence) defaultValue(fields()[11], record.getConversion(11));
        record.radius = fieldSetFlags()[12] ? this.radius : (java.lang.Double) defaultValue(fields()[12], record.getConversion(12));
        record.shapeWkt = fieldSetFlags()[13] ? this.shapeWkt : (java.lang.CharSequence) defaultValue(fields()[13], record.getConversion(13));
        record.deleted = fieldSetFlags()[14] ? this.deleted : (java.lang.Boolean) defaultValue(fields()[14], record.getConversion(14));
        record.colourOnMap = fieldSetFlags()[15] ? this.colourOnMap : (java.lang.CharSequence) defaultValue(fields()[15], record.getConversion(15));
        record.opacityOnMap = fieldSetFlags()[16] ? this.opacityOnMap : (java.lang.Double) defaultValue(fields()[16], record.getConversion(16));
        record.temporary = fieldSetFlags()[17] ? this.temporary : (java.lang.Boolean) defaultValue(fields()[17], record.getConversion(17));
        record.externalReference = fieldSetFlags()[18] ? this.externalReference : (java.lang.CharSequence) defaultValue(fields()[18], record.getConversion(18));
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AvroLocation>
    WRITER$ = (org.apache.avro.io.DatumWriter<AvroLocation>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AvroLocation>
    READER$ = (org.apache.avro.io.DatumReader<AvroLocation>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
