raw.database = ${hive.raw.database}
raw.entity.ASSET=dim_asset
raw.entity.ASSET_NORM=dim_asset_norm
raw.entity.DRIVER=dim_driver
raw.entity.DRIVER_NORM=dim_driver_norm
raw.entity.LIBRARY_EVENT=dim_library_event
raw.entity.LIBRARY_EVENT_NORM=dim_library_event_norm
raw.entity.LOCATION=dim_location
raw.entity.LOCATION_NORM=dim_location_norm
raw.entity.ORGANISATION_GROUP=dim_organisation_group
raw.entity.ORGANISATION_GROUP_NORM=dim_organisation_group_norm
raw.entity.ORGANISATION_SUBGROUP=dim_organisation_subgroup
raw.entity.ORGANISATION_SUBGROUP_NORM=dim_organisation_subgroup_norm
raw.entity.EVENT=fact_event
raw.entity.POSITION=fact_position
raw.entity.SUBTRIP=fact_subtrip
raw.entity.TRIP=fact_trip
raw.entity.TACHO=fact_tacho
raw.entity.DETECTED_EVENT=fact_detected_event

prepared.database = ${hive.prepared.database}
prepared.entity.DRIVER=dim_driver
prepared.entity.EVENT_DESCRIPTION=dim_event_description
prepared.entity.GROUP=dim_group
prepared.entity.LOCATION=dim_location
prepared.entity.VEHICLE=dim_vehicle
prepared.entity.EVENT=fact_event
prepared.entity.EVENT_VIDEO=fact_event_video
prepared.entity.POSITION=fact_position
prepared.entity.SUBTRIP=fact_subtrip
prepared.entity.TRIP=fact_trip
prepared.entity.TACHO=fact_tacho
prepared.entity.VALIDATED_EVENT=fact_validated_event
prepared.entity.CONFIRMED_OVERTAKING_VIOLATION=confirmed_overtaking_violation
prepared.entity.ROAD_CONDITION_VIOLATION=road_condition_violation

prepared.entity.FUEL_TYPE=dim_fuel_type
prepared.entity.GROUP_TYPE=dim_group_type
prepared.entity.LOCATION_TYPE=dim_location_type
prepared.entity.LOCATION_SHAPE_TYPE=dim_location_shape_type
prepared.entity.VEHICLE_STATE=dim_vehicle_state
prepared.entity.VEHICLE_TYPE=dim_vehicle_type
prepared.entity.VIDEO_CHANNEL_TYPE=dim_video_channel_type
prepared.entity.EVENT_VALIDATION_CODE=dim_event_validation_code
prepared.entity.EVENT_PROBLEM_VEHICLE_CODE=dim_event_problem_vehicle_code
prepared.entity.OVERTAKING_VIOLATION_CODE=dim_overtaking_violation_code
