spark.progress.dir=/tmp/progress
spark.checkpoint.dir=/tmp/spark-streaming
spark.checkpoint.interval=0
spark.streaming.driver.writeAheadLog.allowBatching=true
spark.streaming.driver.writeAheadLog.batchingTimeout=60000
spark.streaming.driver.writeAheadLog.closeFileAfterWrite=true
spark.streaming.receiver.writeAheadLog.enable=true
spark.streaming.receiver.writeAheadLog.closeFileAfterWrite=true
spark.streaming.stopGracefullyOnShutdown=true
spark.streaming.backpressure.enabled=true
